### ISSUE TITLE
HS Widgets don't appear in the "Add Widget" menu in the latest update

### ISSUE THREAD

**Issue by mac-user669** [Matchstic/Xen-HTML#100]
**Describe the bug**
I am on the latest Xen HTML version, and when I go into "wiggle mode" on my HS, I can tap the "Add Widget" button. HOWEVER, only iWidgets show up. I have several HS and LS widgets that I would like to be able to add, but am currently unable to do so.

**To Reproduce**
1. Go to the homescreen
2. Enter "Wiggle Mode"
3. Tap "Add Widget"
4. Only see iWidgets

**Expected behavior**
In step 4 above, I would expect to see LockHTML and SBHTML widgets as well as iWidgets

**Screenshots**
Not available

**Smartphone (please complete the following information):**
 - Device: iPhone 5s
 - OS: iOS 12.1.2

**Additional context**
N/A

**Comment by Matchstic** [comment]
This is intended behaviour; the layout of widgets on the filesystem is planned to change soon.

**Comment by Matchstic** [comment]
Fixed for next update
