### ISSUE TITLE
Springboard crash after trying to add a widget in home screen

### ISSUE THREAD

**Issue by jacopicci** [Matchstic/Xen-HTML#105]
Whenever I try to add a widget from the home screen the springboard crashes and the iPhone respring. 
**To Reproduce**
1. Go to the home screen
2. Click on add widget
3. The springboard crashes
**Smartphone
 - Device: iPhone XR 
 - OS: iOS 12.1

Crashreport doesn’t find anything.

**Comment by Matchstic** [comment]
I need a crash log to fix this!

**Comment by Matchstic** [comment]
Probably a duplicate of #122
