### ISSUE TITLE
Widgets added from wiggle menu permanently enabled

### ISSUE THREAD

**Issue by LemonJuiz** [Matchstic/Xen-HTML#106]
**Describe the bug**
When you add a widget from the "wiggle" menu on home screen, there is no way to disable the widget anywhere else. Reinstalling doesn't even help, so I assume it's stored in a file somewhere which is probably unintended
**To Reproduce**
1. Enter wiggle menu
2. Add a widget
3. Exit widget menu
4. Now you have a permanent widget

**Expected behavior**
An option to disable certain widgets (and not just the whole homescreen) from inside settings at least, possibly also the wiggle menu

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone Xs Max
 - OS: 12.1.1

**Additional context**
N/A
I just want my homescreen back :(

*Edits:*
On mobile, hit enter to submit title, submitted entire issue
Also spelling

**Comment by KINGK00PA** [comment]
Still have this issue, is there a solution to it yet?

**Comment by Matchstic** [comment]
Fixed with upcoming update
