### ISSUE TITLE
Home screen status bar time 1 min behind 

### ISSUE THREAD

**Issue by andrewr9165** [Matchstic/Xen-HTML#107]
**Describe the bug
No matter what widget I use, the status bar time is sometimes 1 min behind. Re spring fixes it for an hour or two 

**Smartphone (please complete the following information):**
 - Device: iPhone XS 
 - OS: iOS 12.1.2

**Comment by Matchstic** [comment]
Not really something I can fix, since it's related to the code of whatever widgets you're using.
