### ISSUE TITLE
Unwanted resprings

### ISSUE THREAD

**Issue by puzzledyt** [Matchstic/Xen-HTML#108]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 6]
 - OS: [e.g. iOS 11.1.2]

**Additional context**

**Comment by puzzledyt** [comment]
When on the home screen (iPhone XR) if I swipe up to get to multi-tasking it will respring only if I swipe from the very very bottom of the screen but still happens when I don’t want it too I’m new to jailbreaking so can’t fidn a way to fix this could it be a conflicting tweak? Or simply a bug

**Comment by Matchstic** [comment]
I've not heard of anyone else experiencing this issue. Does removing Xen HTML help?

**Comment by Matchstic** [comment]
No feedback, so closing this issue. Likely caused by a tweak conflict!
