### ISSUE TITLE
iPad Dock Broken In Landscape Mode After Install (Uninstalled and same thing happens)

### ISSUE THREAD

**Issue by ScoutjumperDevs** [Matchstic/Xen-HTML#109]
https://drive.google.com/file/d/1zyLvvGg6dTDi6YweZWFhYXVh_Fb1lNWI/view?usp=drivesdk

**Comment by Matchstic** [comment]
If this happens when Xen HTML is uninstalled as you mentioned, then it’s not the fault of the tweak.
