### ISSUE TITLE
Lockscreen widget don't work

### ISSUE THREAD

**Issue by danifliman** [Matchstic/Xen-HTML#116]
Hi @Matchstic. I hope you can help me. The clock widget on my lockscreen don't show the correct hor. Doesn't update. I have to do a respring to do this.
![unnamed](https://user-images.githubusercontent.com/51306802/58773300-8b444900-858a-11e9-9079-c039a1becf93.jpg)

**Comment by Matchstic** [comment]
Please contact the developer of that widget, that's not likely caused by Xen HTML itself
