### ISSUE TITLE
Widget, camera page overlap

### ISSUE THREAD

**Issue by umtpz** [Matchstic/Xen-HTML#117]
Widget is designed for iPhone XS Max which is loaded on iPhone X has the dark side bars. These bars can get huge with lower resolution devices and overlap on some elements in camera or widget page that prevents tapping on them.

Would be nice to hide (without reloading the) widgets when user swipes to camera or widgets page.

![IMG_2275](https://user-images.githubusercontent.com/21289725/59270167-84d46200-8c59-11e9-9754-d4ba8da4dcc5.PNG)
![IMG_2276](https://user-images.githubusercontent.com/21289725/59270169-84d46200-8c59-11e9-990d-8e54cdd38bf5.PNG)

**Comment by Matchstic** [comment]
This can *technically* be fixed by preventing rendering past the edges of the widget, but you can fix this yourself; make sure to place elements and size the widget based on % of the device's viewport width.

That said, if you're using the size flag in Options.plist that doesn't support device sizing too well (never did in iWidgets either). I'll make a new issue for that.

**Comment by umtpz** [comment]
Its not about the visuals, the widget sizing is the problem. Which prevents tapping on the sides. So widget.plist sizing option is doing that. Since it beeds that extra space to be tapped but that size prevents tapping on lower resolution devices. Have I missed something?

**Comment by Matchstic** [comment]
@umtpz Nope, that's effectively what I'm saying too. Capping the size my end will ensure that the widget doesn't prevent tapping on the sides.

**Comment by umtpz** [comment]
It would be good to have that. Since that will make a lot easier to show the content by giving just padding from top and left and use scaling to make it work on most devices. I wonder if that will change the sizes of the widgets that the ones overlap to the sides when it is done by your end?
