### ISSUE TITLE
XenHTMl crashed my device to safemode on iPhone 4s 

### ISSUE THREAD

**Issue by quanganh123** [Matchstic/Xen-HTML#129]
**Describe the bug**
XenHTML crashed my device into safemode

**To Reproduce**

**Expected behavior**
I don't want it to crash my device into safemode

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 6] iPhone 4s
 - OS: [e.g. iOS 11.1.2] iOS 9.3.5

**Additional context**

**Comment by Matchstic** [comment]
I need a crash log, otherwise I can't fix this!

**Comment by Matchstic** [comment]
No crash log provided, closing this issue.
