### ISSUE TITLE
After I install XenHTML, it crashed my device into safemode

### ISSUE THREAD

**Issue by quanganh123** [Matchstic/Xen-HTML#132]
**Describe the bug**
After I install XenHTML, my device(iphone 4s, iOS 9.3.5) was crashed into safemode and I didn't install any tweak before I install XenHTML(except Xeninfo)

**To Reproduce**

**Expected behavior**
I expected it won't crash my device into safemode

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 4s
 - OS: iOS 9.3.5

**Additional context**
Crashlog: https://drive.google.com/open?id=1RjcQPBpW2UTLmhjW5NXuAjniJIMR6n7I
and many apologises for the lateness of the crash log because I was very busy so I wasn't concentrate on your comment

**Comment by Matchstic** [comment]
I added a potential fix for this in the latest update that i released a few minutes ago - v0.5.4. Please try that version, and let me know if it worked for you!

**Comment by quanganh123** [comment]
It still crashed when I locked my device

**Comment by quanganh123** [comment]
Here is crash log https://www.dropbox.com/s/kkf9lzztqk8co48/SpringBoard-2019-07-30-073514.symbolicated.ips?dl=0

**Comment by Matchstic** [comment]
Please try this new build, and let me know what happens: https://www.dropbox.com/s/l055rnfil5a4wd9/com.matchstic.xenhtml_0.5.4-1_iphoneos-arm.deb?dl=0

**Comment by quanganh123** [comment]
So after I installed the new build, it worked perfectly until I locked my device and it crashed to safe mode

**Comment by Matchstic** [comment]
Crash log please!

**Comment by quanganh123** [comment]
Here https://www.dropbox.com/s/msk13gbv95lhowh/SpringBoard-2019-08-12-153940.symbolicated.ips?dl=0

**Comment by Matchstic** [comment]
@quanganh123 How does this work for you? https://www.dropbox.com/s/esm60e8w0bketa1/com.matchstic.xenhtml_0.5.4-2_iphoneos-arm.deb?dl=0

**Comment by quanganh123** [comment]
So it still crashed and here is crash log https://www.dropbox.com/s/c1jwtuxdrz4vnnf/SpringBoard-2019-08-12-234517.symbolicated.ips?dl=0

**Comment by Matchstic** [comment]
Alright, another build! https://www.dropbox.com/s/euab8rirp8gvshn/com.matchstic.xenhtml_0.5.4-3_iphoneos-arm.deb?dl=0

In this one, I changed the method used to add the 'Add Widgets' button to the Homescreen, which is where your crash is happening. I've also checked in the iOS 9 simulator, and that button is still visible when expected after the change.

**Comment by quanganh123** [comment]
So after I install this version, my device didn’t crash to safe mode in many ways(after I locked the device but it didn’t crashed). Thank you very much

**Comment by quanganh123** [comment]
Just one more question, why any widgets on iphone 4s don’t get the weather but another device like iphone 7 has weather? Is the widget broken on iPhone 4s or something else( I have the location always show and set the weather always)

**Comment by Matchstic** [comment]
Great to hear! You most likely just need to install XenInfo on the iPhone 4s.
