### ISSUE TITLE
iPad landscape still not working properly

### ISSUE THREAD

**Issue by cnassaney** [Matchstic/Xen-HTML#133]
**Describe the bug**
Landscape broken on iPad Pro 12”

**To Reproduce**

**Expected behavior**

**Screenshots**
Screenshot posted on previous bug report

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 6]
 - OS: [e.g. iOS 11.1.2]

**Additional context**
Add any other context about the problem here, such as a link to a crash log.

**Comment by cnassaney** [comment]
Please see screenshot [link](https://github.com/Matchstic/Xen-HTML/issues/89)

**Comment by Matchstic** [comment]
Can you try with a different widget please? It looks to me in that screenshot as if the issue is just the widget in use now.

**Comment by cnassaney** [comment]
![IMG_0430](https://user-images.githubusercontent.com/1091309/62840032-e2c8fa00-bc48-11e9-8e5c-a509ab9f6973.jpeg)
Fluid

**Comment by Matchstic** [comment]
yep, that's broken alright. I'm only able to test this issue in the iOS simulator now, so, realistically I may not be able to fix this one.

**Comment by Matchstic** [comment]
Please let me know how this build works for you: https://www.dropbox.com/s/il69c87r66ah1z0/com.matchstic.xenhtml_0.5.4-4_iphoneos-arm.deb?dl=0

I changed how the initial orientation of the device is retrieved before setting up widgets after a respring.

**Comment by cnassaney** [comment]
Same thing. It looks like it’s pulled back the size of pullover on the iPad Pro. Like the resolution isn’t set properly.

Chesley Nassaney
Chesley.la
cnassaney@mac.com
www.chesley.la
IMPORTANT: The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only. If you have received this email by mistake, please notify the sender immediately and do not disclose the contents to anyone or make copies thereof.

**Comment by Matchstic** [comment]
Not sure I follow what you mean here by 'size of pullover'? Also, odd question, but do you have a hardware keyboard attached to the iPad?

**Comment by cnassaney** [comment]
I do have a keyboard but it’s detached until I need it.

Chesley Nassaney
Chesley.la
cnassaney@mac.com
www.chesley.la
IMPORTANT: The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only. If you have received this email by mistake, please notify the sender immediately and do not disclose the contents to anyone or make copies thereof.

**Comment by Matchstic** [comment]
Additionally, which approach have you used to add the widget to the Homescreen?

1. via the 'Add Widget' button
2. via the Background settings panel

**Comment by cnassaney** [comment]
Have tried both. Interesting that it seems to be fine on lock screen widgets.

Chesley Nassaney
Chesley.la
cnassaney@mac.com
www.chesley.la
IMPORTANT: The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only. If you have received this email by mistake, please notify the sender immediately and do not disclose the contents to anyone or make copies thereof.

**Comment by Matchstic** [comment]
Can you confirm which Settings you're currently using please? I need to know that to help narrow down the issue further.

I've made a couple of assumptions, and made a further new build: https://www.dropbox.com/s/hinme04pn6hzfak/com.matchstic.xenhtml_0.5.4-6_iphoneos-arm.deb?dl=0

Let me know how that fares for you, as well as your current settings used to place the Homescreen widget above.

**Comment by cnassaney** [comment]
Both methods of adding full screen widget in landscape are still cropped to portrait. See attached:

Chesley Nassaney
Chesley.la
cnassaney@mac.com
www.chesley.la
IMPORTANT: The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only. If you have received this email by mistake, please notify the sender immediately and do not disclose the contents to anyone or make copies thereof.

**Comment by Matchstic** [comment]
Can you upload those images to GitHub directly please? I’m not able to view them.

**Comment by cnassaney** [comment]
![IMG_0490](https://user-images.githubusercontent.com/1091309/63054882-89a3d500-be99-11e9-9718-1748eb8813d8.jpeg)
![IMG_0491](https://user-images.githubusercontent.com/1091309/63054887-8c062f00-be99-11e9-908c-39c452784200.jpeg)

**Comment by cnassaney** [comment]
Attached

**Comment by cnassaney** [comment]
Okay.. problem solved. I went in and updated Widgetinfo.plist for various widgets and found the proper sizing. 

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>isFullscreen</key>
    <false/>
	<key>size</key>
	<dict>
		<key>height</key>
		<integer>1024</integer>
		<key>width</key>
		<integer>1400</integer>
	</dict>
	<key>useOptionsPlist</key>
 	<true/>
</dict>
</plist>
`

**Comment by Matchstic** [comment]
Well... that’ll do it alright! At least I’ve made some improvements for orientation handling from this :)
