### ISSUE TITLE
"û" character unsupported 

### ISSUE THREAD

**Issue by LileAuTresor** [Matchstic/Xen-HTML#135]
The character is not displayed correctly (see screenshot : correct word is Août)

![screenshot](https://user-images.githubusercontent.com/42318092/62608585-5ba21c00-b900-11e9-8ce5-21293a1e2521.jpg)

**Smartphone :**
 - Device: iPhone X
 - iOS 12.1
 - XenHTML 0.5.4

**Comment by Matchstic** [comment]
Not caused by me; you need to specify that character by its UTF8 code for WebKit to render properly.

**Comment by LileAuTresor** [comment]
It’s strange, only this character doesn’t render properly. I tried \u00fb &#xFB; &#251; and &ucirc; with the same result. 

I have no other accent problem... What is the correct UTF-8 code for this character knowing that I get the variable from a js file?

**Comment by LileAuTresor** [comment]
I found : it was the font I use who doesn’t have this character...
