### ISSUE TITLE
[HS] Options don’t get updated in the widget

### ISSUE THREAD

**Issue by MrRobotjs** [Matchstic/Xen-HTML#137]
**Describe the bug**
I have installed the “HTC Anímate” iWidget from the June’s Secret Repo. If I go to my HS (Homescreen) and enter “Wiggle Mode” to add the iWidget then the widget will appear. The issue is that the widget is working at all because the configuration options in the “Wiggle Mode” menu don’t seem to be updating it thus causing the widget to be missing some variables. Now the weird part is that if I go to my phones actual settings > xenhtml > homescreen and add the widget there as a BACKGROUND then all the config options that get changed will actually be updated in the widget thus giving me my time and weather. Oh and if I have the widget in my background and I then add it through the “Wiggle Mode” sub menu (basically I’ll have both at the same time) then it seems that it pulls the information from the background config. I’ve also talked to the author of the widget (June) and he confirmed it’s not from his widget but from xenhtml itself.

**To Reproduce**
Maybe only iWidgets are affected or only this iWidget but I’ve used sbhtml and it pulls time and weather info and updates the config fine?
1. Enter Wiggle Mode
2. Click on “Add Widget”
3. Click on “HTC Anímate”
4. Edit options or leave as default
5. Nothing will be displayed other than an empty widget

**Expected behavior**
Well, the per page widget shouldn’t be relying on the background widget’s config to work. It should be able to update its own config in the plist. (I’ve taken a look and it doesn’t seem to update in the plist).

**Screenshots**
https://photos.app.goo.gl/oxXqMBTERhddZ9Ay9
This is just me quick fixing it through the file itself but you can still see my issue. (Not really a fix at all, weather and everything else was still not working by the end of the video)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 7]
 - OS: [e.g. iOS 11.4]

**Additional context**

**Comment by Matchstic** [comment]
Issue has been fixed for v0.5.5. No ETA on release!
