### ISSUE TITLE
Safe mode iPad 3,4 IOS 10.3.3

### ISSUE THREAD

**Issue by MrRafeh** [Matchstic/Xen-HTML#138]
I am using Ipad 3,4 on iOS 10.3.3 jail broken with h3lix
Xenhtml versions > 0.5 makes the iPad crash to safe mode.  Although version 0.48 works
is xenhtml not compatible with iOS 10
https://textbin.net/9fUa1Ltqi7 crash log

**Comment by Matchstic** [comment]
It does support iOS 10, however iOS 10.3.3 is usually a special case and tends to crash like this.

**Comment by MrRafeh** [comment]
Is it an issue that can be fixed? Or just luck if it works on my device

**Comment by Matchstic** [comment]
Sure, it can be fixed. When though? No idea.

**Comment by SlinkyJoey** [comment]
Would this be the case for iOS 10.3.4? As I get the same issue on my iPhone 5 :).

**Comment by Matchstic** [comment]
See: #212
