### ISSUE TITLE
[ios10] changing 12/24 hr clock does nothing

### ISSUE THREAD

**Issue by ZoeyCluff** [Matchstic/Xen-HTML#14]
Changing between 12/24 hr clock does nothing with lockhtml or iwidget based home or lock screen widgets. Weather also doesn't work when inputting a weather code

**Comment by Matchstic** [comment]
This could be related to the widgets you're using, not Xen HTML - I just render them. Can you give me an example that displays this behavior? I'll test it this end.

**Comment by ZoeyCluff** [comment]
They do 24 hour with LockHTML. LS EW93_(N) from Evelyn-YNam works at least in lockhtml, but doesn't display correctly in Xen. LS Momentum from Adit's repo, and CX.LS 7 from Classicxii's repository all don't change the time.

**Comment by ZoeyCluff** [comment]
Ok, at least momentum doesn't work in lockHTML either.

**Comment by ZoeyCluff** [comment]
Got momentum to work in 24 hour mode. needed to enable legacy.

**Comment by ZoeyCluff** [comment]
Ok, they all work with legacy mode.

**Comment by Matchstic** [comment]
Do these widgets all use groovyAPI by any chance? That might be what's causing the need for Legacy Mode - I don't yet automatically detect the usage of groovyAPI!

**Comment by ZoeyCluff** [comment]
Maybe. Momentum's page says Apply with LockHTML or groovyLock.

**Comment by Matchstic** [comment]
So to confirm, all these widgets with the issue work with Legacy Mode? And they all need groovyAPI?

**Comment by ZoeyCluff** [comment]
that appears to be correct.

**Comment by Matchstic** [comment]
Alright cool, in that case this doesn't appear to be a functionality issue of Xen HTML, so will close this issue. However, I will open another to attempt to add auto-detection of needing groovyAPI.
