### ISSUE TITLE
A12 - 12.4

### ISSUE THREAD

**Issue by Gwai** [Matchstic/Xen-HTML#143]
I have an Xs Max on 12.4, when no widget is active xen works, but when i activate any widget. it causes safemode... Is it a tweak or a device/ personal problem?

**Comment by Matchstic** [comment]
Known issue when using Substitute with unc0ver.

**Comment by Gwai** [comment]
and how can i fix it, or do you have to update the tweak?

**Comment by sanboukarasu** [comment]
same problem on XR 12.4

**Comment by MrEagleYT** [comment]
Same thing happened with my XS on 12.4, when or how can this be fixed??

**Comment by Carlos6862** [comment]
Same problem on XR 12.4 too.

**Comment by Carlos6862** [comment]
How can i fix it?

**Comment by Matchstic** [comment]
Fixed, update is on its way to Packix now
