### ISSUE TITLE
Safe Mode Crash A12 12.4

### ISSUE THREAD

**Issue by Burke-J** [Matchstic/Xen-HTML#144]
Hi, I am wondering about a bug on a IPhone XR running iOS 12.4 jail broken on unc0ver. I have been trying to add a widget from the evynw repo called SB E9. Every time I add this widget or any other widget it crashes into safe mode. Any tweaks to fix this or is it just a problem for only my phone?

**Comment by Matchstic** [comment]
I pushed an update to Packix today (not live yet at the time of writing) to fix this
