### ISSUE TITLE
Using XenHTML on home screen breaks FLEX

### ISSUE THREAD

**Issue by qwertyuiop1379** [Matchstic/Xen-HTML#147]
**Describe the bug**
When trying to select items on the home screen using a FLEX tool, nothing is selected but outlines around views are still showed.

**To Reproduce**
1. Open FLEX
2. Try to select something

**Smartphone (please complete the following information):**
 - Device: iPhone 6
 - iOS: iOS 11.3.1

**Comment by Matchstic** [comment]
This is probably related to my touch handling code. Since it’s not a *huge* problem, this is a low priority issue
