### ISSUE TITLE
iOS 13 Support

### ISSUE THREAD

**Issue by Matchstic** [Matchstic/Xen-HTML#150]
Xen HTML needs to be updated to support iOS 13.

Initial TODO list:

- [x] Split out project to modular dylibs per iOS version
- [x] Update postinst script to correctly move the specific iOS version build into place - use `sw_vers -productVersion` to get iOS version in bash
- [x] Adjust all iOS 13 hooks for Lockscreen to account for the CoverSheet.framework refactor @ Apple - will need on-device testing
- [x] Look into why SB Foreground widgets are not rendering
- [x] Look into why the 'Add Widgets' and 'Done' buttons cannot be clicked in the Simulator during Icon Edit mode
- [x] Fix touch on SB Foreground widgets
- [x] Lockscreen widgets flicker/don't show up if a passcode is set (maybe disable LS widgets if WebGL dylib cannot be found?)
- [x] Battery manager is very crash happy
- [x] Lockscreen clock does not become unhidden when switching away from “On all pages”
- [x] Lockscreen idle duration needs a respring to apply
- [x] "Hide Folder Blur" does not work
- [x] "Hide Icon Labels" needs a respring to apply
- [x] ~~cannot tap to exit folders during edit mode~~ not a bug
- [x] Check the following for Dark Mode support: Setup, widget picker, general settings
- [x] Queue evaluateJavaScript calls when widgets are paused
- [x] [iPad only] Drag and drop of SB Foreground widgets doesn't respect page boundaries as intended

**Comment by karkaria** [comment]
Can’t get lockscreen widgets (Smr) to show up. using Xenhtml and XenInfo. iOS 13.2.2

**Comment by Matchstic** [comment]
Support is now finalised
