### ISSUE TITLE
Widgets Not Showing In Notification Center

### ISSUE THREAD

**Issue by RickyX3** [Matchstic/Xen-HTML#151]
So basically my widgets will not show anymore in my Notification center when my phone is unlocked. I have my widgets in the foreground, not the background as it doesn't work anymore with the new updates. It's really troublesome to not be able to see my widget clock when I pull down the notifications. Are you able to look into this? I have the newest version running in an iPhone XR 12.1.2

**Comment by Matchstic** [comment]
Are you using Persistent Mode? If so, fixed for the next update.

**Comment by Carlos6862** [comment]
When i active a tweak, it works, but when i am going to home screen, its freezed. What can i do my friend? 
My phone is XR iOS 12.4
Thanks In advance!!

**Comment by RickyX3** [comment]
Yeah I do have persistent mode on. Should I have it on/off or just wait for the update?
  

  
  

  
  
>

**Comment by Matchstic** [comment]
You’ll want to turn it off for now; watch the progress of issue #148 for updates!
