### ISSUE TITLE
Lock screen don’t show up on iPhone 7+. On ios13

### ISSUE THREAD

**Issue by germanicon** [Matchstic/Xen-HTML#152]
**Describe the bug**
Won’t work on lock screen. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 6]
 - OS: [e.g. iOS 11.1.2]

**Additional context**
Add any other context about the problem here, such as a link to a crash log.

**Comment by Matchstic** [comment]
Duplicate of #150
