### ISSUE TITLE
Iphone X 13.2.2 XenHtml crashing

### ISSUE THREAD

**Issue by Zippas** [Matchstic/Xen-HTML#155]
**Describe the bug**
When I'm installing the "XenHtml" Tweek my phone after respring he restarts to a safe mode instantly after respring. Then when I'm in safe mode I delete the tweek and the phones back to normal working position.

**Smartphone (please complete the following information):**
 - Device: [Iphone X]
 - OS: [IOS 13.2.2]

**Comment by Matchstic** [comment]
Please let me know how this test build fares: https://www.dropbox.com/s/idupjlwleuf8zbu/com.matchstic.xenhtml_1.1~beta1-1_iphoneos-arm.deb?dl=0

**Comment by Zippas** [comment]
Please help me how to install it or what to do, when i Download it from my phone, I can't open the program...

**Comment by Zippas** [comment]
Okey I have installed it! What to do?

**Comment by Matchstic** [comment]
Update is live (v1.1~beta2)
