### ISSUE TITLE
Using reachability causes apps to “hover” over Dock

### ISSUE THREAD

**Issue by MrRobotjs** [Matchstic/Xen-HTML#159]
**Describe the bug**
When the “Homescreen” feature of XenHTML is enabled and using reachability causes apps to “hover” over the dock.

**To Reproduce**
1. Go to “Homescreen” in XenHTML preferences
2. Toggle the feature to ON
3. Return to Homescreen
4. Enable reachability
5. See bug

**Expected behavior**
(Tested by disabling “Homescreen” feature) Supposed to make apps drop down UNDER the dock, not on top of it.

**Screenshots**
https://streamable.com/x2clz

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: 11.3.1

**Additional context**
N/A

**Comment by Matchstic** [comment]
This is a probably an issue relating to how Homescreen widgets can be set to display above icons. Not too sure this can be solved.
