### ISSUE TITLE
[iOS10] Add Tage support

### ISSUE THREAD

**Issue by 0j0k3r** [Matchstic/Xen-HTML#16]
Hi Matt,

I use Tage all the time, and I love the close-out from an app Gesture from the right bottom up. When XenHTML is enabled, and I use that gesture to close my apps, something strange happend. The App closes very fast (faster than without XenHTML), and its a lil glitchy, and the HomeScreen widget disappears for a sec. than it pops back up. Maybe it has something todo with the Activator conflict? Overall Im happy to have XenHTML back on my SpringBoard ;)

**Comment by Matchstic** [comment]
Sounds like when it pops back up, the failsafe to ensure that it redisplays is triggered. I normally hide the widget when in-app to prevent the need for rendering the widget unnecessarily.

**Comment by 0j0k3r** [comment]
Cant make a video of that, but Tage has a 3 day free trial where you can see whats wrong with it ;) On iOS9 I dont have these bug.

**Comment by Matchstic** [comment]
This issue seems to be problematic only when using the "use system animations" option. Since I also don't have access to an iOS 10 device and the issue is purely cosmetic, I'll not be fixing this.
