### ISSUE TITLE
Installing XenHTML possibly caused all SafariWebViews to freeze upon opening in apps systemwide

### ISSUE THREAD

**Issue by badger200** [Matchstic/Xen-HTML#160]
NOTE: I suspect this is an iOS bug, possibly triggered by XenHTML, but I strongly suspect it can also be triggered in other scenarios not involving XenHTML at all.

**Additional Symptoms:**
- Settings.app > **tapping “Safari” instantly crashes Settings app** 100% of the time.
- Settings.app > **tapping Accounts and Passwords > Touch ID prompt & success > instantly crashes Settings app** 100% of the time.
- **Any app that triggers the iOS Saved Passwords autofill mechanism, may either freeze upon successful Touch ID authentication, or simply fail to display anything/autofill any passwords**.

iPad Pro 9.7”
iOS 12.4
Unc0ver 

_2 days later, bug spread to my:_
iPhone 6
iOS 12.4
Unc0ver

⚠️**This bug was one of the worst I have ever experienced on iOS, causing persistent, severe systemwide app breakage, even after rebooting to an unjailbroken state.⚠️☠️😩 It devastated numerous daily apps, and I would describe it as catastrophic.**
To make things worse, it subsequently spread to my iPhone 6 somehow, presumably via something in iCloud syncing, as I never even installed XenHTML on my iPhone. The bug and symptoms were all identical on my iPhone 6. The crashing Settings app, everything I describe. 

So while this may look like a lot of random notes, trust me, you’re gonna be desperate enough to read every word here if you find yourself suffering this bug and you don’t want to erase any data...😁👌🏼

If you don’t mind losing all your Safari History, Cookies, etc., I read several reports that a Settings > Safari > Clear All Data worked. I wasn’t willing to lose anything. Also, I would’ve had to cleaned my History and Cookies via iCleaner or another method, as I described at the top, my Settings > Safari resulted in instant Settings app crash 100% of the time.

**History**
I installed a tweak called “eta s0n” that depended upon XenHTML, to display a countdown clock to clockra1n release. I cannot say for certain that XenHTML was responsible, but it is definitely the prime suspect due to the timing of this issue, as I meticulously trawled the entire filesystem, /tmp/Cydia.log, and my numerous screenshots’ timestamps to best narrow down the time when the bug first began to occur, and the installation of XenHTML was the only obvious coincidental event. Also the fact that issue #65 sounds like a possibly identical bug experience. Viewing @guillaumeseur ‘s attached screen-recording videos, it does appear to display the exact same type of blank WebView window I experienced, but it’s tough to follow his videos without narration. 

While the “eta s0n” lock screen calendar worked, I later noticed that in ALL apps systemwide, **anything that launched a SafariWebView (or whatever an in-app web browser is called) would pop up the window, except it would be completely empty blank white, containing only a blank top UI bar, and a blank full screen window.** None of the usual browser widgets ever load. 

This creates a dead end from which the user cannot escape, and they must force close the app. 

However, I use a handy systemwide Activator popup menu with Action: “Local Back”, and tapping a Local Back via Activator this way, successfully dismissed the frozen white SafariWebView in every single app I tried it in. (Handy if force-closing the app would cause data loss.)

My test-case was the official Gmail app, tapping any hyperlink in an email (my Gmail is set to use Safari for opening links, which actually means in-app browser windows. The test would be invalid if you had this set to Chrome). 

Then, without ever installing the tweak (nor XenHTML) on my iPhone 6, _**somehow this exact same bug spread from my iPad Pro onto my iPhone 6.**_ 

Uninstalling XenHTML and the eta s0n tweaks did not fix anything.

**The good news:** I fixed it on both devices. 
**The bad news:** it took such a Herculean effort, I couldn’t pinpoint/recall exactly what step actually fixed the problem. It took me probably 6 grueling hours to fix the first time, on my iPad Pro, yet still at least 2 hours on my iPhone 6 just 24h later. 

**Notes From My Troubleshooting**
I’m sharing my notes here for future users, because I definitely did fix it, and I would’ve had to erase all settings otherwise. 

- The first thing I did was to use dmesg, syslog (packaged with unc0ver), and oslog (from BigBoss) to observe the system debugging stream during the exact moment I triggered the bug by opening a SafariWebView (in app browser window). However, this did not bear any useful fruit. Neither did my CrashReporter tweak logs, nor my Cr4shed tweak logs.

- I read something on Google about how a .binarycookies file could get corrupted and cause a similar issue. ⚠️**My iPad disk space is perpetually near-full and definitely experiences no-free-space-related bugs on a frequent basis, which possibly played a role here.**

I methodically used Filza to browse all the typical places in the filesystem where Safari data is stored, like:

- /Library
- /System
- /var/containers (Data - use Filza to scroll very bottom left and open “Apps Manager” to avoid deciphering GUIDs, Shared, System, and AppGroup / Application. But keep in mind Safari has folders beyond just the usual Data & Shared. I used Settings.app tweaks like SysInfo that extend the Settings > General > About > Applications > Safari screen to display tappable data storage locations which open directly into Filza. Appster or AppAdmin might also work. I just tried them all!)
- /var/mobile/Containers (same notes as above)
- /var/mobile/Library (Caches folder, as well as any folders containing “safari” or “WebView” etc.)
- /var/root/Library (same notes as above)

I kept looking for obviously-safe-to-delete cache folders under Safari-related folders, and either deleted them, or renamed them if I was scared. The ones with just Cache.db and fsCachedData always seem safe to delete in my experience. 

But I could swear, the bug still didn’t get fixed until sometime after I also began deleting the **com.apple.metal** and **com.apple.opengl** Cache folders too. I don’t know if that was merely coincidental, or causally related. 

I DID generally use the logic of “if the last modified time of everything in the folder (Sort by Time in Filza) is clearly prior to the bug, disregard this folder and proceed to next”.

Also keep in mind:
- **_it’s possible_** something I did fixed the bug, but I failed to recognize it immediately, because **possibly** the fix didn’t take effect until a respring. Thus leaving me confused as to what precisely the root cause & fix were. I definitely did Respring several times during this ordeal. 
- However, I am 95% certain I did NOT reboot either device when I finally managed to fix them. So I wouldn’t waste your time trying a reboot after every file you delete.

PS: This bug was SUCH a pain to solve, if someone asked me to fix it on their device, I wouldn’t even consider it for less than say $500. It was incredibly tedious work!

**Comment by manthan7** [comment]
Hello can you help me every time I install XenHTML and I respring it opens up the blue page and then I cant do anything please help
![88817447-4B8F-416A-A64D-6128A82A058B](https://user-images.githubusercontent.com/60075457/72687677-20ae3200-3ab5-11ea-91c8-79c5ff8396be.jpeg)

**Comment by Matchstic** [comment]
> Hello can you help me every time I install XenHTML and I respring it opens up the blue page and then I cant do anything please help
> ![88817447-4B8F-416A-A64D-6128A82A058B](https://user-images.githubusercontent.com/60075457/72687677-20ae3200-3ab5-11ea-91c8-79c5ff8396be.jpeg)

This isn’t the right thread for this; please create a new one next time.

Regardless, you have some other tweak most likely interfering. Probably one that changes colours of the UI.

**Comment by Matchstic** [comment]
@badger200 Apologies for not responding to your ticket sooner!

Since it happened on other non-jailbroken devices, I suspect it may just have been coincidental - most likely what happened was an underlying WebKit bug that wrecked havoc on your shared Safari data store, just triggered by Xen HTML.

I must admit, the sheer amount of effort you've gone into is impressive! Would you be open to the idea of becoming a beta tester for Xen HTML?
