### ISSUE TITLE
HS.Ryu_006 Fluid Widget not showing in widget list

### ISSUE THREAD

**Issue by LilaQ** [Matchstic/Xen-HTML#164]
After installing HS.Ryu_006 (Packix Repo) it is not showing in the widget list

Settings -> XenHTML -> Homescreen -> BG Widgets -> Add Widget ... not there

**Expected behavior**
It should be there

**Smartphone (please complete the following information):**
 - Device: iPhone X 
 - OS: iOS 13.2.3 (checkra1n)
 - XenHTML 1.1-beta4

**Comment by Matchstic** [comment]
Not an issue with Xen HTML

**Comment by LilaQ** [comment]
It was showing in previous versions - what's the culprit then?

**Comment by Matchstic** [comment]
Nothing has changed regarding where widgets are displayed from in the filesystem. Did you install it from elsewhere after updating to iOS 13?

**Comment by LilaQ** [comment]
I got it from the Packix repo where I think I got from "back in the days" as well on my iPhone 8 :/ It's the official source for it.
