### ISSUE TITLE
XenHTML lockscreen crash.. nothing in lockscreen

### ISSUE THREAD

**Issue by nickmikael** [Matchstic/Xen-HTML#172]
So basically i got this error from 
![4985042C-11DA-4058-B995-D4A281CF038C](https://user-images.githubusercontent.com/60088986/72706264-8e7f5a00-3b98-11ea-8e5d-69cb398151d8.png)
 
Xen html crashes and the best way is to move to safe mode but the problem is i can’t install it i would love widgets to be on my phone... there is nothing on my lockscreen

**Comment by beamspacemonster** [comment]
I have the same issue did you end up finding a fix?

**Comment by JB2020u** [comment]
I am having the same problem. I installed a widget and nothing showed up

**Comment by nickmikael** [comment]
Hey~ guys updatw: i managed to fix it... okay you have to keep clicking everything on the screen if it says back at the top right that means that is progress keep clicking it until it actually respire

**Comment by Matchstic** [comment]
Make sure to install version 1.1.1~release of Xen HTML, which does not have this issue.

**Comment by Matchstic** [comment]
A new Setup UI has now been built which solves this
