### ISSUE TITLE
Boot into Safe Mode after Install XenHTML IOS 13.3 iPhone X

### ISSUE THREAD

**Issue by ivan385i** [Matchstic/Xen-HTML#173]
After I Install XenHTML in my IPhone X iOS 13 he boots into safe mode

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.3

**Additional context**
The Crashlog: https://www.dropbox.com/s/i9421938fgtqhzh/Datei%2026.01.20%2C%2023%2009%2019.txt?dl=0

**Comment by Matchstic** [comment]
That crash is caused by Snowboard
