### ISSUE TITLE
message popups

### ISSUE THREAD

**Issue by YBTyler** [Matchstic/Xen-HTML#174]
okay so i got xen html and the lock screen crashed, then i did a hard reset and backed up my files and jailbreaked again, now this pop up is showing up 
![AB0C2E5F-1666-4C95-9663-C166979AAC02](https://user-images.githubusercontent.com/60673940/73790859-d2f92100-4766-11ea-8db0-a08db0e43aa3.jpeg)

it wont show up on cydia, so i cant uninstall it. all im wondering is how can i delete with like filza or something. please respond as it is getting pretty annoying seeing that popup
 
im using an iphone 6s on ios 13.3

**Comment by Matchstic** [comment]
You can install again in Cydia to “register” the tweak’s files, then remove in Cydia to remove it
