### ISSUE TITLE
XenHTML Installation Complete Buttons Disappearing

### ISSUE THREAD

**Issue by helpforsupport** [Matchstic/Xen-HTML#176]
So I keep installing XenHTML but every time I install it it brings me to this screen that says, Installation Complete! But about a second later, it disappears and I can click continue even though the button is invisible but I don't know what to do from there because it won't let me do anything else. Please help.

**Comment by Matchstic** [comment]
Are you on iOS 13.3?

**Comment by Matchstic** [comment]
A new Setup UI has now been built which should solve this
