### ISSUE TITLE
Particles showing

### ISSUE THREAD

**Issue by orenifer** [Matchstic/Xen-HTML#177]
**Describe the bug**
“Background Particles” showing when now enabled.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.3

**Comment by Matchstic** [comment]
Not enough information for me to understand what exactly your issue is...?

**Comment by orenifer** [comment]
What exactly do you need to know?

**Comment by Matchstic** [comment]
Is the widget enabled for the Lockscreen or Homescreen? Foreground or Background? Via the “Add Widget” button on the Homescreen?

If it’s the Lockscreen, do you use Persistent Mode?

**Comment by orenifer** [comment]
![61BF7BBE-6587-467C-BFBF-C860C0A4F8B3](https://user-images.githubusercontent.com/60127508/77511515-e4fb6400-6e79-11ea-9b30-0ad6e30f4758.jpeg)
![0724CADE-3525-45BE-86A2-3784EE2C5A8C](https://user-images.githubusercontent.com/60127508/77511525-e9c01800-6e79-11ea-9537-4cedfa551ccb.jpeg)
![0D3BAC51-807B-4682-B8A0-99994EF2C8EE](https://user-images.githubusercontent.com/60127508/77511526-eaf14500-6e79-11ea-8e2f-5c71560d30d4.jpeg)
![07EAE7C9-55CE-4796-AC4F-7EEF5688D4CE](https://user-images.githubusercontent.com/60127508/77511527-eaf14500-6e79-11ea-9114-d500cde43ccf.jpeg)

**Comment by orenifer** [comment]
Widget (particles) is not enabled for either. 
That’s the problem.

**Comment by Matchstic** [comment]
It looks like you've managed to drag the Particles widget into the Spotlight page. No idea how you managed that!

**Comment by orenifer** [comment]
yes! Figured that out by accident.
Thanks mate
