### ISSUE TITLE
Handle DeviceOrientationEvent.requestPermission for iOS 13

### ISSUE THREAD

**Issue by mileyvirus** [Matchstic/Xen-HTML#178]
**Is your feature request related to a problem? Please describe.**
When using `deviceorientation`, `devicemotion` or `orientationchange` in iOS 13+ devices, we now have to call `DeviceOrientationEvent.requestPermission()` (or whatever) first to make users accept/deny the usage of the gyroscope.

And it only works in `https://`…

See https://medium.com/flawless-app-stories/how-to-request-device-motion-and-orientation-permission-in-ios-13-74fc9d6cd140 for example.

**Describe the solution you'd like**
Bypassing the permission request altogether and accepting it by default.

**Comment by mileyvirus** [comment]
I found [this snippet](https://stackoverflow.com/questions/58969959/devicemotion-and-deviceorientation-in-wkwebview-ios-13) to test the behaviour on a widget and it confirms indeed that we can't get accelerometer data anymore.

Apparently Xen HTML doesn't display the permission alert because it doesn't use `uiDelegate` ([`WKUIDelegate` docs here](https://developer.apple.com/documentation/webkit/wkwebview/1415009-uidelegate)).

One commenter claims they solved it by just adding one line inside `viewDidLoad` and confirming type of `ViewController` to `WKUIDelegate`.
```swift
webView.uiDelegate = self
```

LockBackground.html

```html
<html>
    <style>
        #container{
            margin: 20px; 
            padding: 20px
        }
        #deviceType{
            text-align: center; 
            font-family: Arial, Helvetica, sans-serif; 
            font-size: 3rem;
            font-weight: bold; 
            color: #08f
        }
        #permission{
            padding: 2rem 5rem;
            background: #08f;
            color: white; 
            margin-top: 30;
            font-family: Arial, Helvetica, sans-serif; 
            font-size: 3rem;
            border: none; 
            border-radius: 1rem
        }
        #permissionStatus{
            text-align: center; 
            font-family: Arial, Helvetica, sans-serif; 
            font-size: 2.5rem;
            font-weight: 600; 
            color: red;
            margin-top: 30px
        }
    </style>
    <body>
        <div id="container">
                <div id="deviceType"></div>
                <div style="text-align: center">
                    <button id="permission">Ask for permission</button>
                </div>
                <div id="permissionStatus">Pending</div>
        </div>
    </body>
    <script>

        if (typeof DeviceMotionEvent.requestPermission === 'function') {
            document.getElementById('deviceType').innerText = 'iOS 13'
            document.getElementById('permission').addEventListener('click', function () {
                console.log('button clicked')
                DeviceMotionEvent.requestPermission().then(response => {

                    // This is showing "denied" without showing any permission popup
                    console.log(response)
                    document.getElementById('permissionStatus').innerText = response

                }).catch(console.error)
            });
        } else {
            // ignore this case for processing
            console.log('non iOS 13')
            document.getElementById('deviceType').innerText = 'non iOS 13'
        }
    </script>
</html>
```

**Comment by Matchstic** [comment]
Thanks a lot for this report, will look at it for 1.1.3

**Comment by mileyvirus** [comment]
Thank you! Can’t wait :)

**Comment by Matchstic** [comment]
For my own reference, here's when/how this behaviour changed: https://www.mail-archive.com/webkit-changes@lists.webkit.org/msg139132.html

**Comment by Matchstic** [comment]
@mileyvirus Please check that this build now works: https://www.dropbox.com/s/nc267hbxlzduz6c/com.matchstic.xenhtml_1.1.3~beta1_iphoneos-arm.deb?dl=0

**Comment by mileyvirus** [comment]
Thanks for the test build!

It kinda works but it forgets the permission state as soon as the webview unloads so it’s not ideal. 

Right now the behavior is: gyro data is inaccessible > user interaction (tap) > permission is granted without showing iOS’ own native permission dialog > gyro data is available > unlock phone > come back > reset.

**Comment by Matchstic** [comment]
Unfortunately, I think that may just be how it works internally in WebKit; have to request permission before usage no matter what. 

Since you’re able to actually get data though, I’m considering this fixed

**Comment by mileyvirus** [comment]
Let me run a few more tests today and I’ll get back to you to see if I can save the permission state. That way we can also add a snippet to the docs

**Comment by mileyvirus** [comment]
It works! You just have to request the permission on load and you're all set. Thank you very much!

Here's a snippet to show how to request it (I'm a JS noob):
```js
if (typeof DeviceMotionEvent.requestPermission === 'function') {
	// It's an iOS 13 device.

	// Let's request DeviceMotion or DeviceOrientation on load, it will automagically get granted.
	window.onload = function() {
		DeviceMotionEvent.requestPermission().then(response => {
			// Permission is granted, from here you'll be able to access DeviceMotion or DeviceOrientation.
		}).catch(console.error)
	};

} else {
	// If DeviceMotionEvent is unavailable, we got an iOS < 13 so we can normally access  DeviceMotion or DeviceOrientation.
}
```

**Comment by mileyvirus** [comment]
I don't know why or what happened but it randomly stopped working… In every widget in which I use requestPermission() onLoad without user interaction now don't work anymore.

This started happening after a sbreload respring.

So I debugged the webview in Safari and it logs that requesting deviceMotion requires user interaction. So I chose the tester widget I posted before and I pressed the button once and after that removed it. Now all the widgets work again after 1 button press. They seem to only work until a respring tho…

**Comment by Matchstic** [comment]
I've narrowed down where the check for user interaction occurs, and am currently looking at overriding it.

**Comment by Matchstic** [comment]
@mileyvirus Please test this build: https://www.dropbox.com/s/x2vtb86m28dfvfs/com.matchstic.xenhtml_1.1.3~beta2_iphoneos-arm.deb?dl=0

I am now able to run your example for window.onload immediately after a respring, with the request for permission always being granted.

**Comment by mileyvirus** [comment]
Thanks for the last commits, I'm now able to immediately access deviceOrientation data even on resprings. I tested in multiple scenarios, on different phones with different jailbreaks on iOS 13 and it works everywhere.

Bloody good work!

**Comment by VictorDenisenko** [comment]
How can I remember the permission? Now I need to ask it every time when I reopen the browser!

**Comment by Matchstic** [comment]
> How can I remember the permission? Now I need to ask it every time when I reopen the browser!

There’s no browser involved in Xen HTML widgets, not entirely sure what you mean. Either way, if it’s broken, it’s gonna stay that way. I don’t intend to update this project any further.
