### ISSUE TITLE
Enter safe mode when using XenHtml + A-Font.

### ISSUE THREAD

**Issue by Minj-0726** [Matchstic/Xen-HTML#180]
If you use a-font and xenhtml at the same time, it enters safe mode.
Only one of the two tweaks is available.

In unc0ver 4.0.2 you can apply two tweaks at once,
But, Enters safe mode when respring.

This issue did not occur at all in the ios12 version.
I'm having problems after upgrading to ios13.3.

I think the two tweak compatibility in ios13 is not good.
Is there any way to solve this problem?

**Comment by Matchstic** [comment]
Please re-test this with the latest version of unc0ver

**Comment by Matchstic** [comment]
I’ve found a solution to this, coming next update
