### ISSUE TITLE
Harder time pulling up the Notification Center on LS

### ISSUE THREAD

**Issue by lEnderBOSSl** [Matchstic/Xen-HTML#181]
**Describe the bug**
I have a harder time pulling up the previous notifications on my lock screen, and have to start from lower to pull it up. The widget I have is a simple date and clock widget that is at the top of my screen and should at no point have any chance of interfering with me pulling the Notification Center up.

**To Reproduce**
1. Installed LS Digita Clock from Brian’s repo
2. Placed the widget where the normal iOS time is and hid the iOS one from settings
3. Lock phone and attempt to pull from normal hight to bring up notifications
4. Only able to pull notifications from lower than usual

**Expected behavior**
I expected to pull my notifications from the normal hight as if the tweak was not installed.

**Screenshots**
None.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 11 Max Pro]
 - OS: [e.g. iOS 13.1.1]

**Additional context**
None.

**Comment by Matchstic** [comment]
The widget may be sized such that it’s the entire height of your display. If so, it’ll be grabbing touch events until the “cutoff region” I enforce to allow notifications access
