### ISSUE TITLE
SafeMode with SafeShutdown

### ISSUE THREAD

**Issue by 7Iff5** [Matchstic/Xen-HTML#182]
**Describe the bug**
When entering SafeShutdown mode (at 5% battery or manually with CC module) the iDevice enters in safe mode.

**To Reproduce**
1. Launch SafeShutdown to enter in Safeshutdown state
2. It instantly enters in safe mode

**Expected behavior**
The device has to enter in SafeShutdown mode to prevent it to completely shutdown and preserve the jailbreak. The iDevice wakes up at 5% battery in Jailbroken state.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max
 - OS: 13.3

**Additional context**
Here is the link to the log :
https://www.dropbox.com/s/axwvfas334hp43t/Fichier%2019-02-20%2013%2020%2035.txt?dl=0

**Comment by Matchstic** [comment]
Please check if this new build fixes the issue: https://www.dropbox.com/s/nc267hbxlzduz6c/com.matchstic.xenhtml_1.1.3~beta1_iphoneos-arm.deb?dl=0

**Comment by 7Iff5** [comment]
> Please check if this new build fixes the issue: https://www.dropbox.com/s/nc267hbxlzduz6c/com.matchstic.xenhtml_1.1.3~beta1_iphoneos-arm.deb?dl=0

Works flawlessly, no bugs at the moment. With this one, entering in « SafeShutdown » mode does not enters the iPhone into Safe Mode anymore.

Big thanks.

**Comment by Matchstic** [comment]
Great, thanks for testing it!
