### ISSUE TITLE
iOS 13.3 iPhone 11 “hide lock screen dots” not working

### ISSUE THREAD

**Issue by bossbmw335is** [Matchstic/Xen-HTML#188]
I’m finding that hide lock screen dots are not working, or if I’m misinterpreting it, there is no action that happens if it’s toggled, my assumption of what it is, is removing the two buttons on the bottom where the one on the left turns on the flashlight/torch, whilst the right opens the camera, if I’m incorrect about what it does, plz tell me I’m dumb, if I assumed the right thing, then plz help, I can’t get the proper foreground layout I want if those buttons and lock icon are present (but from what I see you can’t get rid of the lock icon, so I think I’m sol there) so plz help so I can get this looking decent

**Comment by Matchstic** [comment]
Some options are missing on newer devices, which encompasses the option to hide the two buttons you’re mentioning. Next update fixes this.

**Comment by Matchstic** [comment]
Version v1.1.2 of Xen HTML is now available, adding the missing options next to the page dots option.
