### ISSUE TITLE
Next event information

### ISSUE THREAD

**Issue by gezlnh8u** [Matchstic/Xen-HTML#190]
There is no option to enable next event info with the widget. I don’t know if this is a bug or it was just not added to be enabled ?

**Comment by Matchstic** [comment]
For widget information, please use XenInfo.

**Comment by gezlnh8u** [comment]
> For widget information, please use XenInfo.
> […](#) Yes, that does not work, I have Events, alarms and reminders checked. But they don't show on the lock screen.



> On 25 Feb 2020, at 04:14, gezlnh8u ***@***.***> wrote: ﻿ There is no option to enable next event info with the widget. I don’t know if this is a bug or it was just not added to be enabled ? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Matchstic** [comment]
In that case, make sure to use a widget that already supports event information.
