### ISSUE TITLE
Unresponsive UI

### ISSUE THREAD

**Issue by NinjaBG** [Matchstic/Xen-HTML#191]
While in lockscreen(not notification center) when trying to scroll notifications, the UI rarely responds. When the camera is opened, I can’t take pictures nor zoom in/out

1. Lock
2. Wake screen
3. 3D touch camera toggle
4. Try to take picture

**Smartphone (please complete the following information):**
 - Device: iPhone X(Global)
 - OS: iOS 13.3 
 - Jalibreak: checkra1n 0.9.7 beta

**Comment by Matchstic** [comment]
Cannot reproduce. What widget is in use, and in the Foreground or Background?

**Comment by NinjaBG** [comment]
Foreground Widgets. EW.WdgtPack.18_LS1 and LS EW.Battery. Tried disabling EW.Battery, didn’t help

**Comment by NinjaBG** [comment]
So I find out where the screen reacts and where it doesn’t. On the right side it will register input, but on the left side it won’t(that’s in camera)

**Comment by Matchstic** [comment]
Sounds like a duplicate of #117
