### ISSUE TITLE
Phone restarts 

### ISSUE THREAD

**Issue by ashek998** [Matchstic/Xen-HTML#194]
**Describe the bug**

**To Reproduce**
1. Install uncover
2. Click on jailbreak
3. Successful 
4. Randomly while using phone it suddenly restarts and agian we need to jailbreak

**Expected behaviour**
It should not restart itself. 

**Screenshots**
NA
**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 6s plus]
 - OS: [e.g. iOS 13.3]

**Additional context**
Uncover version 4. Above causing this problem. It should never get restart or reboot until user do action restart/power off.

**Comment by Matchstic** [comment]
That’s a kernel panic, and could be caused by a variety of things. Probably not Xen HTML
