### ISSUE TITLE
Safe mode with Shortlook

### ISSUE THREAD

**Issue by xmvssx** [Matchstic/Xen-HTML#196]
Hi, 
When i install shortlook my iPhone X (13.3.1) go to the safe mode but when i delete Xen HTML, shortlook work perfectly.

Three days ago i was on 13.3 and my iPhone work normaly with theses two tweaks.

I tried to disable the tweaks one by one by looking at the errors on Cr4hsed but it doesn't change anything. I send you some of them maybe you will see something :

https://pastebin.com/WMVuxgA0
https://pastebin.com/hHyXfEL7
https://pastebin.com/P1eAWzzb

Best regards,

**Comment by Matchstic** [comment]
Unfortunately, none of those logs appear to show Xen HTML to be the cause. Plus, make sure to remove cracked tweaks from your device.
