### ISSUE TITLE
Scroll lag

### ISSUE THREAD

**Issue by NetworkAdapter** [Matchstic/Xen-HTML#197]
Even with no widgets enabled, scrolling (with your finger on the screen consistently) is noticeably laggier.

Go to a long article online (webview stutter is more noticeable) and scroll with your finger held down the entire time. You will see ‘micro stutters’.

Disabling xen in iCleaner (or uninstalling) resolves this issue.

 - Device: [iPhone XR]
 - OS:        [iOS 13.3]
-  JB:         [u0]

**Comment by Matchstic** [comment]
Please try disabling XenHTML_WebGL.dylib in iCleaner, then test this issue. That's the only thing that potentially could cause this.

**Comment by NetworkAdapter** [comment]
This does seem to have fixed my issue. Would you like for me to record the issue?

**Comment by Matchstic** [comment]
No need, I’ll have to do some work to improve this issue in that dylib

**Comment by Matchstic** [comment]
Linking for my own reference: 

https://github.com/WebKit/webkit/blob/f6c14c04d674d64c878e38a778867d6e90b8d8c7/Source/WebKit/Platform/cocoa/LayerHostingContext.mm#L64

https://trac.webkit.org/changeset/245183/webkit

**Comment by Matchstic** [comment]
@NetworkAdapter Please try this build, which has a revised approach to implementing the WebGL helper: https://www.dropbox.com/s/rzebxevxxvyh885/com.matchstic.xenhtml_1.1.4~alpha1_iphoneos-arm.deb?dl=0

**Comment by NetworkAdapter** [comment]
> @NetworkAdapter Please try this build, which has a revised approach to implementing the WebGL helper: https://www.dropbox.com/s/rzebxevxxvyh885/com.matchstic.xenhtml_1.1.4~alpha1_iphoneos-arm.deb?dl=0

This appears to have completely fixed my issue!

**Comment by luchi222** [comment]
i have an iphone xr with ios 13.5 that has stuttering on the screen, can you help me solve it?
