### ISSUE TITLE
iPhone X 13.3 Safe Mode

### ISSUE THREAD

**Issue by nturner03** [Matchstic/Xen-HTML#199]
**Describe the bug**
After installing Xen HTML, I respring my device and it sends me straight to safemode. Then after uninstalling Xen HTML, it then boots back into the regular jailbreak.

**To Reproduce**
1. Install Xen HTML
2. Click on respring after installing package
3. Safemode

**Expected behavior**
It is expected to boot regularly into jailbreak after the respring and to be able to use Xen HTML normally.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: 13.3

**Comment by Matchstic** [comment]
Already fixed for the next update
