### ISSUE TITLE
Weather Forecast Icons Not Showing Up on Homescreen

### ISSUE THREAD

**Issue by Sakura20** [Matchstic/Xen-HTML#205]
I need help please.
I don’t know why im having this issue with Xen HTML. I added the weather widget to my home screen but the weather icons aren’t showing up on my homescreen. I tried to reset the settings in Xen Html setting but that didn’t work so I tried to uninstall the tweak and reinstall it again but it didn’t fix the issue either. Before it was working perfectly fine and the iwidget was working perfectly fine showing the weather forecasts icons on my home screen. But I don’t know why it’s not working anymore. I noticed that it stopped working like it’s supposed to back when I uninstall ReProvision old version when that tweak was no longer working but I don’t see how that could cause the problem. It’s already been a few months since then but I still can’t get Xen HTML to work properly. I tried everything that I could think of but none of those help fixed the problem. Please help. Is there anything I can do to fix this and get the weather forecasts icons to show upon my home screen?

**Comment by Matchstic** [comment]
You're probably missing XenInfo.

In Xen HTML 2, you won't need to install anything extra to get widgets to work properly.
