### ISSUE TITLE
Lock screen bug

### ISSUE THREAD

**Issue by ipaduser1** [Matchstic/Xen-HTML#207]
Its a little bug that I do find very annoying it a glitch with the widgetS on the lock screen that if you swipe to your camera it makes the side of the screen black

Steps to reproduce the:
1. Swipe left on the lock screen

Just to fix the bug so it doesn’t get in my way

**Smartphone (please complete the following information):**
 - Device: iPad 6th Gen
 - OS: 13.1.2

**Comment by Matchstic** [comment]
Duplicate of #117
