### ISSUE TITLE
Drains Battery since Update 13.3.1

### ISSUE THREAD

**Issue by Fipps1** [Matchstic/Xen-HTML#208]
With Xen HTML activated the (brandnew 100% capacity) battery of an iPhone SE looses >50% of it's load within 24 hours with the phone completely inactive/idle/standby. With Xen HTML deactivated the drainage for the same time is less than 20%.

This happens since the OS has been updated from 13.3 to 13.3.1.

1. Completely charge battery up to 100% (just for testing!)
2. Leave phone sleeping untouched
3. Check battery level after 24 hours

**Expected behavior**
Constant discharge reaching less than 50% after given time

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 13.3.1

**Additional context**
Also installed: Xeninfo
Battery, Statusbar, Weather activated. All other options deactivated.
Happens also with only the XenHTML_Loader.dylib activated.

**Comment by Fipps1** [comment]
Problem seems solved!

I "accidently" updated to 13.4 and, after seeing Checkra1n doesn't work with that at the moment, recovered to 13.3.1. And since the problem seems to be gone!

Charged to 99% on wednesday 11 pm. And now, saturday 10 am, still have 70% left.

**Comment by Matchstic** [comment]
Great, thanks for the update!
