### ISSUE TITLE
Hiding default lock screen clock not working 0.3.6-1

### ISSUE THREAD

**Issue by TheRoar02** [Matchstic/Xen-HTML#21]
After updating today to 0.3.6-1 I can no longer hide the default date and time so it just appears along side my custom clock. ![Like this:](https://imgur.com/a/rQjJh)

**Comment by TheRoar02** [comment]
https://imgur.com/a/rQjJh

**Comment by Matchstic** [comment]
Any chance you have a tweak like HideMeX installed that provides clock hiding? It's possible it's overriding my hiding.

**Comment by TheRoar02** [comment]
The problem goes away when I disable hotdog with iCleaner but it had been working fine before I updated and no settings had been changed. Also after looking thru hotdogs settings, I wasn't able to find a setting that hides the clock.

**Comment by Matchstic** [comment]
The technique I use to hide the clock changed in the last build; I'll be providing the current solution as an optional way to hide the clock, but use the old by default.

Matt

**Comment by Matchstic** [comment]
Issue has been sorted for the next update (going live shortly) by defaulting to hiding the clock on all pages - the old method. The new method can be selected as an optional way of hiding it.
