### ISSUE TITLE
Xen HTML - Safe Mode problem on IOS 10.3.3 after installation 

### ISSUE THREAD

**Issue by TheNameJef** [Matchstic/Xen-HTML#212]
**Describe the bug**
It all happens when i deleted Xen HTML (at a specific version that's below 0.5) and then download it back again at the latest version. After installation, i restarted  my springboard and it crashes me into Safe Mode, no other versions worked for me.

**Expected behavior**
Would run smoothly without any interference 

**Smartphone:**
 - Device: iPhone 5
 - OS: iOS 10.3.3 

**Crash Log**
https://justpaste.it/6kqys

**Comment by Matchstic** [comment]
@TheNameJef Please let me know if this build works for you: https://www.dropbox.com/s/nchyuk9w5p1w0z0/com.matchstic.xenhtml_1.1.5~alpha1_iphoneos-arm.deb?dl=0

**Comment by TheNameJef** [comment]
Didn't work, just like the previous 
Here's the crash log if you need it
https://justpaste.it/5e56b

**Comment by Matchstic** [comment]
Thanks, how about this one?

https://www.dropbox.com/s/c77w2l6fz8pjaj1/com.matchstic.xenhtml_1.1.5~alpha5_iphoneos-arm.deb?dl=0

**Comment by TheNameJef** [comment]
Splendid! It actually worked, thank you for fixing it.

**Comment by Matchstic** [comment]
Ace! The fix will be live on Packix in a few hours
