### ISSUE TITLE
GPG Error NO_PUBKEY 86929D21B1ACBFF2 when running "apt update" in terminal

### ISSUE THREAD

**Issue by 0utlawActual** [Matchstic/Xen-HTML#215]
**Describe the bug**
A GPG Error is encountered when running `apt update` in terminal when https://xenpublic.incendo.ws repo is present in Cydia sources. Towards the end of apt-update, the following output is given.

```
...
Fetched 4,273 kB in 52s (82.7 kB/s)
Reading package lists... Done
W: GPG error: https://xenpublic.incendo.ws ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 86929D21B1ACBFF2
iPhone:~ root#iPhone:~ root#
```

**To Reproduce**
1. Open any terminal window on iPhone (e.g. NewTerm2) or ssh into iPhone
2. Become root user `su root` and type password
3. Issue `apt update`
4. Wait for update to finish and see "W: GPG error: https://xenpublic.incendo.ws ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 86929D21B1ACBFF2" towards the end

**Expected behavior**
`apt-update` should finish without GPG errors

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: iOS 13.3.1

**Additional context**
This GPG error does not appear when updating sources through Cydia.

**Comment by Matchstic** [comment]
Since this works in a package manager, I won’t be looking further at this

**Comment by Mmoi-Fr** [comment]
May we have the (gpg) public key used for the repos? This would be great ;)

**Comment by Matchstic** [comment]
In all honesty, there’s probably not much point in getting it. I don’t plan to put new versions of Xen HTML on the beta repository; the latest is on Packix.
