### ISSUE TITLE
backdrop-filter: blur causes battery drain/lag

### ISSUE THREAD

**Issue by FreddieDev** [Matchstic/Xen-HTML#219]
**Describe the bug**
I discovered [SB Box](https://repo.packix.com/package/com.daniell.sbbox/) was causing battery drain/stuttering on my device.

When looking into it, I found removing the experimental webkit CSS style `-webkit-backdrop-filter: blur(5px);` and instead just using a translucent background solved the issue.

The blur added a great flair to my device and while this fixes the issue, the translucent appearance looks quite dull.

**To Reproduce**
1. Download [SB Box](https://repo.packix.com/package/com.daniell.sbbox/)
2. Feel the lag when opening the widget positioner, having FT calls, opening apps etc.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: 13.3

**Comment by Matchstic** [comment]
Due to how WebKit works, I can't do anything about this.
