### ISSUE TITLE
threedeeboard.dylib Cause springboard to crash 

### ISSUE THREAD

**Issue by AYHAMP** [Matchstic/Xen-HTML#220]
Springboard keep crashing every time I use notifications panel or pressing them to use 3D Touch the problem seem to from threedeeboard.dylib 
I’m on iPad5 ,3
iOS 13.2.3

**Comment by Matchstic** [comment]
If the issue is from “threedeeboard.dylib” (Cylinder), then, why are you asking for support in Xen HTML?

**Comment by AYHAMP** [comment]
Ya right I removed it stopped crashing thanks a lot I didn’t know it was
because of this thanks again for the reply and hard work
