### ISSUE TITLE
Iframe/api bug

### ISSUE THREAD

**Issue by AplAddict** [Matchstic/Xen-HTML#237]
My widget "Local Covid Case Counter" available for free on twickd uses an iframe an when that widget is enabled XenHTML constantly launches safari and tries to open that site I'm not sure if it's due to the iframe or the api it's calling

**Comment by Matchstic** [comment]
Ah. I guess that might happen due to my “redirect to Safari” code that usually runs when setting window.location!

**Comment by Matchstic** [comment]
Leaving open until beta 2, for testing upon release

**Comment by Matchstic** [comment]
Please let me know if this new build helps: https://www.dropbox.com/s/hpzx8tcrpe0l0fv/com.matchstic.xenhtml_2.0~beta1.3_iphoneos-arm.deb?dl=0

**Comment by Matchstic** [comment]
Fixed in beta 2
