### ISSUE TITLE
Xeninfo Cellular/WIFI information not working with XenHTML 2

### ISSUE THREAD

**Issue by AplAddict** [Matchstic/Xen-HTML#238]
Widgets are not displaying cellular/WiFi information with XenHTML 2. I noticed this with my HS13 widget however it worked fine with xeninfo installed so I assume it's like that with all widgets.

**Comment by Matchstic** [comment]
That information is not yet available in my compatibility layer. See: https://github.com/Matchstic/libwidgetinfo/issues/2

**Comment by Matchstic** [comment]
Marking as invalid because I plan to add this, and am tracking progress in the linked ticket.
