### ISSUE TITLE
the weather channel app opens like crazy

### ISSUE THREAD

**Issue by albertoh83** [Matchstic/Xen-HTML#240]
iphone 11 pro max ios 13.3 uncover 5.0

xenhtml 2.0
The weather channel app opens itself many times as well as safari links

Screenshot
![55453900-A762-4DF7-A5D6-2A859F9E7761](https://user-images.githubusercontent.com/26281187/82839788-24542a00-9e96-11ea-8a87-64dcb7abd561.png)

**Comment by Matchstic** [comment]
I would imagine this is caused by a widget using an iFrame; see #237 for a similar report

**Comment by Matchstic** [comment]
Leaving open until beta 2, for testing upon release

**Comment by Matchstic** [comment]
Please let me know if this new build helps: https://www.dropbox.com/s/hpzx8tcrpe0l0fv/com.matchstic.xenhtml_2.0~beta1.3_iphoneos-arm.deb?dl=0
