### ISSUE TITLE
Some calls functions from Xeninfo don’t work in XenHTML2

### ISSUE THREAD

**Issue by paraskcd1315** [Matchstic/Xen-HTML#243]
**Describe the bug**
Some js window.location functions of Xeninfo to openurl or openspotlight for example doesn’t work in Xenhtml 2, 
Syntax used is

`window.location = 'xeninfo:openurl:google.com'; ` for open url

`window.location = 'xeninfo:openspotlight'; ` for opening spotlight..

I haven’t tried openapp function so not sure

The music functions to start/pause skip/back music does work though.

**To Reproduce**
An example will be one of my Widgets Moira Modules, the searchbar I made that uses openurl has become lifeless, only works when xeninfo is installed.

**Expected behavior**
Expected behaviour is that when inputting something to searchbar and pressing enter, it should open Safari with Google and the search query I wrote.

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max with unc0ver
 - OS: iOS 13.5

 - Device: iPad Pro 10.5 with Chimera1n
 - OS: iOS 13.5

**Additional context**
n/a

**Comment by Matchstic** [comment]
All except openspotlight are now hooked up for beta 2

**Comment by Matchstic** [comment]
Opening spotlight won't be supported in Xen HTML 2, so I'm happy to close this ticket
