### ISSUE TITLE
Widgets are loading weird

### ISSUE THREAD

**Issue by isaac19197** [Matchstic/Xen-HTML#245]
iOS 13.4.1
Checkra1n
2.0 -beta1

Widgets css and JS are messing up. There shouldn’t be a new way to write JS or CSS. Please fix this thanks. 
![FEBE91C1-0A67-4912-8F4C-40AA8D49575E](https://user-images.githubusercontent.com/24795969/82862086-c868c000-9eec-11ea-9a67-0d504d19eb75.png)
![Uploading 533366A5-CBC8-44B5-A371-F9E68A937FCD.png…]()

**Comment by Matchstic** [comment]
As mentioned in the release notes, this is expected right now - not all widgets work!
