### ISSUE TITLE
Weather12 by CodeOne not working

### ISSUE THREAD

**Issue by RBKLO** [Matchstic/Xen-HTML#246]
**Describe the bug**
It fails to load the weather data.

**To Reproduce**
1. Go to 'lockscren widgets'
2. Click on 'add weather widget to foreground'
3. Select any settings(doesnt matter)

**Expected behavior**
Load the weather data.

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus
 - OS: iOS 13.5

**Comment by Matchstic** [comment]
Thanks, this is already noted in #236
