### ISSUE TITLE
Widget selection not in alphabetical order

### ISSUE THREAD

**Issue by 0j0k3r** [Matchstic/Xen-HTML#25]
Im running iOS 11.1.1 on my iPhone 8 and have the latest XenHTML build (thanks for that Matt) installed. The Homescreen Widget selection is not in alphabetical order, I didnt tested that  with LockScreen widgets.

**Comment by Matchstic** [comment]
Fixed in commit https://github.com/Matchstic/Xen-HTML/commit/b1724ef25a42a0d875f7ca6cb9d293e4acab6d14, will be included in the next update

**Comment by 0j0k3r** [comment]
nice, thanks Matt for updating XenHTML 👍🏼

**Comment by 0j0k3r** [comment]
nice, thanks Matt for updating XenHTML 👍🏼

**Comment by 0j0k3r** [comment]
nice, thanks Matt for updating XenHTML 👍🏼
