### ISSUE TITLE
Battery Widget and actual battery differ

### ISSUE THREAD

**Issue by Dogrules23** [Matchstic/Xen-HTML#253]
**Describe the bug**
My battery percentage says 89%, the lock screen widget says 77%. 

**To Reproduce**
Unsure
**Expected behavior**
I expected the widget and actual battery life to be the same. 

**Screenshots**
![7A789FDA-1F7A-426C-9A1D-E7EF3888C282](https://user-images.githubusercontent.com/41657798/82981219-76da3700-9fb9-11ea-9852-71ea46e54db0.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 13.5

**Additional context**
I used a USB-C charger to charge it via desktop PC. Don’t know if that makes a difference though.

**Comment by Matchstic** [comment]
Do you use Apple’s battery case?

**Comment by Dogrules23** [comment]
Nope, too luxury for me.

**Comment by Dogrules23** [comment]
Update: after a respring, all my widgets seem to be working properly

**Comment by Matchstic** [comment]
In that case, it was probably just showing old data! I'll consider this as "fixed", since a respring solved it.
