### ISSUE TITLE
List of possible return values for certain endpoints

### ISSUE THREAD

**Issue by strafe** [Matchstic/Xen-HTML#258]
I'm currently using the `weather.now.condition.description` inline to display the current weather condition. I want to display a glyph based on that condition (I assume I'll need to switchover to the callback approach to implement that but I can't seem to find an exhaustive list of all possible return values.

**Comment by Matchstic** [comment]
To do that, use `weather.now.condition.code` instead. That is the numerical version, because the description is for displaying only; it will get translated to the user's current language.
