### ISSUE TITLE
Widget Settings in Options.plist not working in the new Widget directory

### ISSUE THREAD

**Issue by iiMshl** [Matchstic/Xen-HTML#259]
**Issue:**
When placing a widget with Options.plist in the new central folder and try to change the settings it just says no settings available.

Device: iPhone 11 Pro Max
iOS: 13.5
Xen HTML version: 2.0~beta1

It does however read the Options.plist just fine if it is placed in the iWidgets folder

**Comment by Matchstic** [comment]
Please can you confirm if this build works for you? https://www.dropbox.com/s/mdjqtltmbqyu917/com.matchstic.xenhtml_2.0~beta1.4_iphoneos-arm.deb?dl=0

**Comment by iiMshl** [comment]
Yes this build works great! Thanks.
