### ISSUE TITLE
Annoying Haptic Feedback

### ISSUE THREAD

**Issue by mateow99** [Matchstic/Xen-HTML#261]
Every few touches on the home screen causes haptic feedback and it doesn’t happen when I disable “allow touch on background” but I need that on

**Comment by 0neGuyDev** [comment]
Are you sure this is even XenHTML's fault? Afaik XenHTML doesn't have haptic feedback anywhere... If you have Rose it may be causing it, I had a similar issue some time ago...

**Comment by mateow99** [comment]
I just realized it was fluid widget causing it so I'll reach out to that dev instead
