### ISSUE TITLE
Unable to install widgets

### ISSUE THREAD

**Issue by GrosPanda** [Matchstic/Xen-HTML#262]
**Describe the bug**
When I try to install more widgets my settings app simply crashes.

**To Reproduce**
1. Go to Xen HTML
2. Click on more widgets
3. Click on any one of them
4. Settings app crashes

**Expected behavior**
Bringing to the download for the widget

**Screenshots**
[VIDEO HERE](https://streamable.com/d7zd6p) 

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max 
 - OS: iOS 13.5

**Comment by Matchstic** [comment]
Already fixed in the latest beta at https://xenpublic.incendo.ws

**Comment by GrosPanda** [comment]
My bad sorry 😅
