### ISSUE TITLE
Constant respring

### ISSUE THREAD

**Issue by aminambani** [Matchstic/Xen-HTML#263]
Since I installed xen2 am facing constant respring , when I disable its all fine
iOS 13.5
iPhone X

**Comment by JannikCrack** [comment]
I have the same problem since the beta 2 iPhone 11 Pro unc0ver 5.0.1

**Comment by Matchstic** [comment]
Does this build help? https://www.dropbox.com/s/ionftwsa2ciw362/com.matchstic.xenhtml_2.0~beta2.2_iphoneos-arm.deb?dl=0

**Comment by JannikCrack** [comment]
Unfortunately it’s the same after some min respring and always searching location

Kind regards,
JannikCrack
Am 3. Juni 2020, 14:44 +0200 schrieb Matt Clarke <notifications@github.com>:

**Comment by Matchstic** [comment]
Please try the following:

1. Turn off Location Services
2. Respring

If that helps, I can start to pin down the issue

**Comment by JannikCrack** [comment]
Didn’t helped, respring after 2:45

Kind regards
JannikCrack
Am 3. Juni 2020, 14:56 +0200 schrieb Matt Clarke <notifications@github.com>:

**Comment by Matchstic** [comment]
Are you able to hook up the device to Console.app on a Mac? If so, please filter the results for SpringBoard and monitor the logs. With any luck, something should be posted as to why the respring happened.

**Comment by JannikCrack** [comment]
Yeah I can do it. How can I send you these logs? Maybe add some specific logs so we see where it respring?

Kind regards,
JannikCrack
Am 3. Juni 2020, 15:08 +0200 schrieb Matt Clarke :

**Comment by Matchstic** [comment]
Best thing would be to email me at matt@incendo.ws, with the log contents attached as a .txt file.

I'm going to be looking at 30 seconds before then after the respring in the logs, which should give me some indication of what's going on.

**Comment by JannikCrack** [comment]
How can I save a log as .txt file?

Kind regards,
JannikCrack
Am 3. Juni 2020, 15:37 +0200 schrieb Matt Clarke <notifications@github.com>:
> Best thing would be to email me at matt@incendo.ws, with the log contents attached as a .txt file.
>
> I'm going to be looking at 30 seconds before then after the respring in the logs, which should give me some indication of what's going on.

**Comment by Matchstic** [comment]
It should be a matter of highlighting the relevant section of logs, hitting CMD+C, then pasting into an empty document in TextEdit.

Another option would be to paste here: https://ghostbin.co/

**Comment by Matchstic** [comment]
Closing in favour of tracking this issue in #270
