### ISSUE TITLE
Battery API Maximum Capacity Inaacurate

### ISSUE THREAD

**Issue by al5ina5** [Matchstic/Xen-HTML#265]
I tweeted you about this issue. https://twitter.com/youngseebi/status/1267580009306259468

**Describe the bug**
The maximum capacity value is not accurate. It fluctuates based on battery. With a brand new phone (less than a week old), my max cap fluctuated from under 200 to over 3,000. The cap should not change in a short period, and should represent long-term health of the battery. 

**To Reproduce**
Simply display or read the battery max cap at any time.

**Expected behavior**
The max cap should only change over time, alongside the life and health of the battery. In my case, on a new phone, it should match the design value or be very close to it.

**Screenshots**
https://imgur.com/a/u1GbFFu
https://imgur.com/a/j9yUll7
As you can see in the second screenshot, the max cap value (Health) is very close to the battery charge level. As I charge my phone, the cap raises. As the battery dies, the cap lowers.

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.5

**Additional context**
I think that summarizes it. :)

**Comment by Matchstic** [comment]
Fixed for beta 3 - I was using incorrect battery info to grab the current max capacity.
