### ISSUE TITLE
Weather card stuck on loading

### ISSUE THREAD

**Issue by Dogrules23** [Matchstic/Xen-HTML#269]
**Describe the bug**
The weather card on my home screen is stuck in loading. 

**To Reproduce**
Unsure

**Expected behavior**
The current weather to be shown on the card. 

**Screenshots**
![23EA0EAA-3409-4BD1-8D5A-1C45681ABC69](https://user-images.githubusercontent.com/41657798/83676068-172aef80-a5a8-11ea-9e53-1abdcb27fa34.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 13.5

**Additional context**
Respring did not fix this issue and I am connected to WiFi. Even attempted disconnecting from WiFi. Could be conflicting with Kalm which displays weather on the lock screen? Also tried deleting and re-adding the widget and that didn’t change anything.

**Comment by Matchstic** [comment]
Please try rebooting and then running your Jailbreak tool again. 

Do you use Cydia, Sileo, Installer or Zebra?

**Comment by Dogrules23** [comment]
I use Cydia. I will try the reboot and rejailbreak to see if that fixes it. 

Harrison S. Burd

**Comment by Dogrules23** [comment]
Rebooted and rejailbroken. The loading is still there.

**Comment by Matchstic** [comment]
Hmm. Likely is the same cause as #266 - the background daemon isn’t running for some reason

**Comment by Matchstic** [comment]
Closing in favour of tracking this issue in #270
