### ISSUE TITLE
Settings won't be applied for Widget …

### ISSUE THREAD

**Issue by Aeneon** [Matchstic/Xen-HTML#27]
Hi Matt,

I#ve experienced a strange new Bug in the latest Version of Xen HTML : It's not possible to apply the Widget Settings. Do you've changed anything behind the Logic of this ? With the last Version everything was fine and working.

Greetings,
Aeneon

**Comment by Matchstic** [comment]
Are we talking a Config.js or Options.plist here? Plus, what error (if any) are you seeing?

**Comment by Aeneon** [comment]
I'm using a "Options.plist" and everything was fine with the old Version. The Problem is, I can change ( and apply ) nearly everything in the Widget Settings, which looks like not a Problem with the "Options.plist". But after applying the Changes made with "Options.plist" ( the Changes will be loaded correctly ), nothing will be applied in the Theme on Lockscreen or in the Preview. I've attached my complete Widget, if you need it. All necessary Code can be found in "/Scripts/logic.js" : [XenWatch.zip](https://github.com/Matchstic/Xen-HTML/files/1887118/XenWatch.zip) …

Hope this helps. The Problem is, I don't see any Errors. Is there a possibility for debugging Code from Xen HTML, to see if it's a Problem with my "logic.js" ?

**Comment by Matchstic** [comment]
Just making sure (as a similar mistake was made with my internal testers), you are clicking “accept” at the preview after the widgets Settings UI is closed? Clicking “cancel” there will not apply any changes.

Matt

**Comment by Aeneon** [comment]
Yes, I've done it …

**Comment by Matchstic** [comment]
Are you able to see the result of changed settings after a respring?

**Comment by Matchstic** [comment]
Looks like you're not the only one seeing this! Might be something weird on my end when injecting Options.plist into a widget.

**Comment by Matchstic** [comment]
I've fixed this in commit https://github.com/Matchstic/Xen-HTML/commit/6474b1578112b83e7a1775017a5649f2bfe78372 , which will be included in the next update.
