### ISSUE TITLE
widgetinfod appears to not load, leading to missing or old data showing, alongside constant resprings

### ISSUE THREAD

**Issue by Matchstic** [Matchstic/Xen-HTML#270]
**Describe the bug**
It seems that in some cases, widgetinfod enters a restart loop. This has the effect of either missing data, or old data showing that never updates.

In some cases, widgetinfod is being clearly killed by jetsam, causing SpringBoard to restart when connection is halted unexpectedly.

**To Reproduce**
Seemingly caused by beta 2.1

**Expected behavior**
N/A

**Screenshots**
N/A

**Smartphone (please complete the following information):**
Reports are typically 13.5 on using checkra1n or unc0ver

**Additional context**
N/A

**Comment by Matchstic** [comment]
Linked tickets: 

#263
#269 
#266

**Comment by Matchstic** [comment]
Current testing shows that raising the jetsam limit of widgetinfod to 100MB appears to solve the issue.

**Comment by Potterd** [comment]
Reboot and rejailbreak (Checkra1n) seemed to help to resolve the issue on one device that was exhibiting the problem while running beta 2.8.

**Comment by Matchstic** [comment]
Making good progress here. I've changed the IPC layer to now use rocketbootstrap, which so far has cleared up the constant respring issue seen by one reporter.

**Comment by Matchstic** [comment]
Keeping open until beta 3 is released

**Comment by jawsoftware** [comment]
I have still this problem (iPhone 6s, 13.5). If enabled, I get frequent widgetinfod crashes and strange timeout/malfunctioning/slow WiFi. Disabling widgetinfod using DaemonDisabler crashes and WiFi problems disappear, but I miss system data for widgets.
I have less widgetinfod crashes downgrading to beta3.1, but still get slow network.
