### ISSUE TITLE
All widgets crash

### ISSUE THREAD

**Issue by coastsidekyle** [Matchstic/Xen-HTML#272]
**Describe the bug**
When you try to open a repository under “More Widgets”, “XenHTML”, it crashes the settings app.

**To Reproduce**
1. Go to settings
2. Click on XenHTML
3. Scroll down to More Widgets
4. Try opening a repository 
5. See error

**Expected behavior**
When you go to the XenHTML settings, and open a widget repo, you expect it to open the repo or open it in safari

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 13.5

**Additional context**
Add any other context about the problem here, such as a link to a crash log.

**Comment by Matchstic** [comment]
Fixed in the latest public beta

**Comment by coastsidekyle** [comment]
How would I upgrade to the public beta?
