### ISSUE TITLE
XenHTML Crashes Settings App Clicking More Widgets

### ISSUE THREAD

**Issue by brennenclarke** [Matchstic/Xen-HTML#273]
XenHTML is crashing Settings app every time I click on more widgets and choose any repo. Is there a known fix for this?
iOS 13.5, unc0ver jailbreak. Most recent Xen 1.1.5~release installed from Packix repo.

**Comment by brennenclarke** [comment]
I also for the life of me cannot remove any widgets from home screen once they’re there. There are 2 background home screen widgets running and murdering my ram and there’s no visible way to remove them. 
1. I uninstalled and reinstalled. They came back. 
2. Can’t swipe right to delete, can’t find a way to delete. The x in the view of the widget does nothing. 
3. Clicking factory reset of settings in the support option does nothing at all. 
Feeling really defeated here.. any help would be appreciated.

**Comment by Matchstic** [comment]
Crashing is fixed in the most recent public beta

Hit the red “-“ to the left of the widget name. You may have a theme that changes its colour, or obscures it.
