### ISSUE TITLE
Allow touch on background causes haptic feedback

### ISSUE THREAD

**Issue by alex-vincent** [Matchstic/Xen-HTML#274]
When "allow touch on background" is on, (homescreen with Fluid widget) swiping pages on SpringBoard causes a small haptic feedback.

I am running iPhone XS 13.5. Others also reporting issue here:
https://www.reddit.com/r/jailbreak/comments/gtv1gq/help_xen_html_causing_haptic_feedback_on_home/

**Comment by Matchstic** [comment]
From what I understand, this is caused by the fluid widget itself, not Xen HTML. It likely uses a JS API for haptic feedback which now works on iOS 13.5
