### ISSUE TITLE
Removing foreground widget 

### ISSUE THREAD

**Issue by abcdefg7123me** [Matchstic/Xen-HTML#276]
So I wanted to see what a foreground widget was, so I edited the home screen and added one. It was cool and all until I couldn’t remove it, no matter what I did. I searched it up and nothing appeared. I need help, how do you remove a foreground widget?

**Comment by Matchstic** [comment]
You simply edit icon edit mode, and hit the “X” on the top left of a widget. If it’s not visible, try moving the widget.
