### ISSUE TITLE
Lockscreen widgets load-up time

### ISSUE THREAD

**Issue by alexmen14** [Matchstic/Xen-HTML#28]
Sometimes my lockscreen widgets take time to load-up.

This problem doesn’t really happen when i start the phone.
The problem usually happens once i lock my device and turn it right back on, then it takes like about 2-5 sec before the widgets are visible, is this a bug or is it normal?

For the rest very awesome tweak 😉

**Comment by Matchstic** [comment]
This is completely normal; webpages, which widgets effectively are, do take some time to initially load up!

**Comment by asoksevil** [comment]
There's a new issue open where we might be able to disable this.
