### ISSUE TITLE
Harbor 3

### ISSUE THREAD

**Issue by ElliottNess79** [Matchstic/Xen-HTML#280]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 6]
 - OS: [e.g. iOS 11.1.2]

**Additional context**
Add any other context about the problem here, such as a link to a crash log.

**Comment by ElliottNess79** [comment]
Doesn’t seem to work with Harbor 3

**Comment by Matchstic** [comment]
You need to provide more information than that, **including filling out the template in your first comment**.

What doesn't work?

**Comment by Matchstic** [comment]
Closing due to lack of feedback
