### ISSUE TITLE
Random resprings and freezes after installing xen html

### ISSUE THREAD

**Issue by YoJames2019** [Matchstic/Xen-HTML#281]
**Describe the bug**
After installing xenhtml I get random freezes for a few seconds, random resprings, and xenhtml appears to be trying to access my location at all times

**To Reproduce**
install xenhtml with the tweaks i have

**Smartphone (please complete the following information):**
 - Device: Iphone 8
 - OS: iOS 12.4

**Additional context**
CrashReporter doesn't detect the random respring as a crash

**Installed Tweaks**
Activator: 1.9.13\~rc1
SnowBoard: 1.3.3\~Beta3
CrashReporter (SparkDev): 1.17.2
TechSupport Framework (SparkDev): 1.5.2
libcrashreport (SparkDev): 1.1.2
libpackageinfo (SparkDev): 1.1.4
libsymbolicate (SparkDev): 1.9.2
SmallSiri: 1.2.2
No3DLines: 1.2.1-1
AppSync Unified: 76.0
PreferenceOrganizer 2: 4.0.8
KarenPrefs: 1.5
KarenLocalizer: 1.0.5
Cuboid: 0.1.1
BetterCCXI: 1.6.0
FlatSafariURL: 0.0.1
NoPageDots7: 1.0
NoSBLandscape: 0.0.3
WinOS: 0.1
Win10: 0.2
TriSet: 0.3
Slide Mod by uhoffi: 0.0.1
Slide: 0.5
Piano: 0.5
Pearl: 0.4
Nyx: 2.1
mySB: 1.2
Knect: 0.1
Greenbay: 0.0.1
iOSDroid: 0.6
Foto: 0.1
CW70: 0.6
VPanels: 0.3
CW70Grid: 0.2
Mnml: 1.5.3
Meta: 0.0.5
FrontPage: 1.5.4
Astral: 0.2
0xygen: 0.2
LockPlus Pro: 1.8.9
Filza File Manager: 3.7.6-20
AppStore++: 0.9.11
Sileo: 1.8.2
Sylph: 1.3\~Beta.1
YouTube Reborn: 1.0.3.1
AppList: 1.5.16
ReProvision: 0.5.2\~EOL
PullOver Pro: 2.1
FloatingDockPlus: 1.3.4.1
Bolders: 1.2.2-2
NewGridSwitcher: 1.1.0
Graide: 1.2
APT 1.8 (apt-key): 1.8.2-1
Core Utilities (/bin): 8.30-3
APT 1.8 Strict (lib): 1.8.2-sileo6
gzip: 1.10-1
LendMyPhone 2: 1.1.2
SilentScreenshot: 1.2
SnapBack: 2.0.1
PowerApp: 5.0
Moonshine: 1.3.1
Cuttlefish: 1.2
Cylinder: 1.1
Springfinity: 1.1.8
RealCC: 1.0.2
Magma: 1.0.4
PowerModule: 1.3.1
CCSupport: 1.2.2
BetterSettings: 0.1.3
libCSColorPicker: 1.0
libCSPreferences: 1.1.6
HUDPlayer: 2.0.2
Free Market: 1.0
NewTerm (iOS 10 – 13): 2.4
Substrate Compatibility Layer: 99.3
Tweak Injector: 1.4.2-sileo
Substitute: 0.1.3-coolstar
Cydia Compatibility Package: 2.3
Debian Utilities: 4.8.4-2
iPhone Firmware (/sbin): 0-1
Z Shell (zsh): 5.7.1
Tape Archive: 1.31-1
system-cmds: 805.220.1-3
shell-cmds: 203-3
sed (Dummy): 4.8
Profile Directory: 0-4
OpenSSH: 7.9p1
New Curses: 6.1-1
XZ Utils: 5.2.4-1
LibreSSL: 2.8.3
grep (Dummy): 3.4
GNU Privacy Guard: 1.4.23
Find Utilities (Dummy): 4.7
Debian Packager: 1.19.4-1
Diff Utilities: 3.7
Darwin Tools: 1-7
Core Utilities (Symlinks): 8.30-1
Base Structure: 1-5
bzip2: 1.0.6-2
Bourne-Again SHell: 4.4.18-1
APT 1.8 Strict: 1.8.2

**Comment by Matchstic** [comment]
This is fixed in the upcoming beta 3.
