### ISSUE TITLE
Can’t remove widget added to XenHtml lock screen 

### ISSUE THREAD

**Issue by Shableigh226** [Matchstic/Xen-HTML#282]
**Describe the bug**
I can add as many widgets as I wish to the XenHtml lock screen, but I do not have the option to remove widgets.

**To Reproduce**
1. Go to Settings
2. Scroll down to Xen HTML
3. Click on lock screen 
4. Click on foreground widgets under Configure 
5. Click on the date and time widget called “Scripted”
6. There is no option to remove the widget. If you long press the Scripted widget from the foreground widgets there is no option to drag it to trash. If you swipe there is no option to delete it. 

**Expected behavior**
I expected to be able to click into the widget I want to remove and see a prompt to delete it, or be able to drag and drop it into trash, etc.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 11 Pro Max 
 - OS: [e.g. iOS 13.3.1]

**Additional context**
Add any other context about the problem here, such as a link to a crash log.

**Comment by Matchstic** [comment]
To remove a widget, just tap on the red “-“ next to its name.

You may have a theme that obscures it
