### ISSUE TITLE
Cannot view Timer display on Lockscreen

### ISSUE THREAD

**Issue by igobythisname** [Matchstic/Xen-HTML#286]
**Describe the bug**
with Xen Html enabled, the Timer (from native Clock app) display on the lock screen is not visible

**To Reproduce**
1. enable any Lockscreen widget w/Xen Html
2. set Timer in Clock app
3. view lock screen

**Expected behavior**
to see the Timer display or have a feature in settings to Show/Hide it

**Screenshots**
available upon request

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max
 - OS: iOS 13.5

**Additional context**
if the timer cannot be displayed, please advise to any timer widgets; i seriously have spent the past hour or more looking into this issue before I came here to report it as a bug; all the posts on reddit/r/iosthemes re: 'timer on the lockscreen' have gone unanswered :(

**Comment by Matchstic** [comment]
You can set the 'Hide Lockscreen Clock' mode to Main Page Only, then the timer will be visible in the Today View on the left of the Lockscreen.
