### ISSUE TITLE
Uniaw widget does not update weather and time LS and SB. ipad pro 13.5 2nd generation

### ISSUE THREAD

**Issue by ZeppelinLuis** [Matchstic/Xen-HTML#287]
** Describe the error *
The UniAw Marty de Buuf widget does not update the weather and time on ipad pro second generation.

**Play**
1. I download widget
2. settings / xen html / lockscreen / add widget / Uniaw
3. widget / wather API settings "default"
4. locscreen does not update weather and time.
my location is mexico and the time of the widget does not show it
** Expected behavior **
time and hour according to my location.

** Screenshots **
Annex capture of the widget not updated and my location on the first page of homescreen.

** Smartphone (fill in the following information): **
  - Device: iPad Pro 2020
  - SO: iPasOS 13.5

** Additional context **
UniAw.log
(2020-06-11 04:23:26 +0000) ERROR: TypeError: null is not an object (evaluating 'document.getElementById ("WeatherInfoBG"). Style')
Call Stack:
noInfo @ file: ///var/mobile/Library/LockHTML/UniAW-MartyTribute/AnemoneHTML/JavaScript/main.js: 1293: 44
j @ file: ///var/mobile/Library/LockHTML/UniAW-MartyTribute/AnemoneHTML/JavaScript/jquery.min.js: 2: 26865
fireWith @ file: ///var/mobile/Library/LockHTML/UniAW-MartyTribute/AnemoneHTML/JavaScript/jquery.min.js: 2: 27674
x @ file: ///var/mobile/Library/LockHTML/UniAW-MartyTribute/AnemoneHTML/JavaScript/jquery.min.js: 4: 11155
abort @ file: ///var/mobile/Library/LockHTML/UniAW-MartyTribute/AnemoneHTML/JavaScript/jquery.min.js: 4: 8988
file: ///var/mobile/Library/LockHTML/UniAW-MartyTribute/AnemoneHTML/JavaScript/jquery.min.js: 4: 10544

**Comment by ZeppelinLuis** [comment]
![6BFFBC35-F5A7-4941-912B-3C4CFF85DAE2](https://user-images.githubusercontent.com/35675371/84402220-cc256380-abc9-11ea-87e9-999af5317d86.jpeg)
![758D9817-FCA4-499F-98EA-BC51A6F2F59E](https://user-images.githubusercontent.com/35675371/84402240-cfb8ea80-abc9-11ea-8024-4599d952e5c3.jpeg)

**Comment by Matchstic** [comment]
Closing because this is probably a problem in the widget, not Xen HTML
