### ISSUE TITLE
Text Not Showing When Typing On Background Widget / Scrolling Issues

### ISSUE THREAD

**Issue by BobtheUltimateProgrammer** [Matchstic/Xen-HTML#288]
**Describe the bug**
When typing in a home screen background widget (e.g. a notes widget), the text does not show up. Additionally, scrolling does not work.

**To Reproduce**
1. Get a notes widget (if you can’t find one, I can post the code for a widget I found)
2. Put it on the home screen as a background widget.
3. Type into the widget. Nothing shows up.
4. For the scrolling issue, attempt to scroll downward. Nothing happens.

**Expected behavior**
The text should show up.
The widget should scroll down.

**Screenshots**
See this video: https://imgur.com/a/NaUlglI

**Smartphone (please complete the following information):**
 - Device: iPad mini 4
 - OS: iPadOS 13.5 (using unc0ver)

**Additional context**
This was not an issue on iOS 12.1.1 with unc0ver.

**Comment by Matchstic** [comment]
Honestly, touch on background widgets is a hack so I'm not completely surprised that this doesn't work correctly. The "solution" is probably to use this widget as a foreground widget instead (via the 'Add widget' button when editing icons)
