### ISSUE TITLE
Option to persist the current Lockscreen widgets in memory

### ISSUE THREAD

**Issue by Matchstic** [Matchstic/Xen-HTML#29]
When locking the device, there is a short delay in which widgets load when re-waking the device. Persisting widgets in memory after an unlock would resolve this, but will result in greater memory usage (and perhaps battery usage also) outside of the Lockscreen.

**Comment by asoksevil** [comment]
Hi!

Yes this was suggested by me. I believe we should have this option and let users decide whether they want to do it or not! 

Also, I believe there is no settings preferences for lockhtml themes and it would be helpful to have one where you can manually type the exact coordinates of the widget position. When you import them they are stored in the background layer but you can't know for sure the exact X Y position.

**Comment by Matchstic** [comment]
Implemented in 13b3c30f23088262655c243948a9a6590e3e2147

**Comment by asoksevil** [comment]
Hey Matt, thanks for the update. 

Is this currently implemented in the latest version of the repo?

**Comment by Matchstic** [comment]
Not yet no, there’s a couple more things I want to get sorted before pushing a new build.

**Comment by me246813579** [comment]
Any updates?

**Comment by me246813579** [comment]
@Matchstic Do you have a private fix?

**Comment by Matchstic** [comment]
I have no idea what private fix you mean? I’ve not worked on Xen HTML for a little while now, the latest changes are all public.

**Comment by me246813579** [comment]
Oh, I mean a fix that's not released
