### ISSUE TITLE
Widgetinfod crashes 1380 times in 24 hous

### ISSUE THREAD

**Issue by kuangwoo** [Matchstic/Xen-HTML#290]
**Describe the bug**

Widgetinfod crashes 1380 times in 24 hous

**To Reproduce**

**Expected behavior**

**Screenshots**
![F509DABB-884E-4F4E-82BA-016A0B0070B2](https://user-images.githubusercontent.com/62356622/84600520-ef8b2f80-aea3-11ea-9f86-ac1a0ab76c70.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: 13.5

**Additional context**
Add any other context about the problem here, such as a link to a crash log.

**Comment by Matchstic** [comment]
A screenshot doesn’t help, sorry.

Regardless, I have found a fix in an upcoming update.
