### ISSUE TITLE
Reset all settings. 

### ISSUE THREAD

**Issue by Bdub92** [Matchstic/Xen-HTML#291]
**Describe the bug**
When you try to click on the reset all settings button you get no response nor reset. 
**To Reproduce**
1. Go to '...'support. 
2. Click on '....'Reset all settings
Attempt to reset all settings.
**Expected behavior**
To reset. 
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 6] xs max. 
 - OS: [e.g. iOS 11.1.2]13.5 

**Additional context**
Add any other context about the problem here, such as a link to a crash log.

**Comment by Matchstic** [comment]
Works fine on v2.0~beta3.
