### ISSUE TITLE
Widgets not working 

### ISSUE THREAD

**Issue by Lullabi** [Matchstic/Xen-HTML#294]
**Describe the bug**

After installing XenHTML, I try to add widgets to the homescreen and after doing so, they don’t work. For example, the music widget doesn’t show what’s currently playing or the weather widget doesn’t display any information.

**To Reproduce**

**Expected behavior**

For the widgets to load the correct information

**Screenshots**

Can’t add screenshots due to being on mobile but can add if needed 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 11]
 - OS: [e.g. iOS 13.4.1]

**Additional context**
Add any other context about the problem here, such as a link to a crash log.

**Comment by Matchstic** [comment]
Which version of Xen HTML are you using?

**Comment by Matchstic** [comment]
Closing to lack of feedback
