### ISSUE TITLE
widgetinfod Crashing a lot!

### ISSUE THREAD

**Issue by khal0o0** [Matchstic/Xen-HTML#295]
I keep getting crashes report like 5 times today!
iOS 13.5 IPHONE 11
Report link:
https://pastebin.com/BnU5iDCb

**Comment by jawsoftware** [comment]
I can confirm the issue. In my case (iPhone 6s, 13.5, checkra1n) it crashes frequently and keeps the CPU at 100% (verified with htop from terminal). Crashes become less frequent downgrading to previous beta release.
As a collateral issue it gives WiFi connectivity problems with apps until I disable the daemon with DaemonDisabler.

I accidentally found a quick method to check the problem with an app:
1) Install Angry Words from AppStore
2a) without widgetinfod: running the app works correctly and connects to internet
2b) with widgetinfod running: the app reports connection problems at startup (seldom it succeeds to complete startup) and when in match stops dragging tiles after 2 or 3 tiles movemen, laggingt. From terminal you can see CPU is at 100% and lots of memory is used by widgetinfod.
3) switching to DaemonDisabler and disabling widgetinfod, CPU usage go way down and connection problems and lags disappear.

**Comment by Matchstic** [comment]
Thanks, this is a known issue.

Does this build help? https://www.dropbox.com/s/hd3g9sz37u82oyj/com.matchstic.xenhtml_2.0~beta3.9_iphoneos-arm.deb?dl=0

**Comment by jawsoftware** [comment]
> Does this build help? 
Definitely! Just installed and reenabled the daemon. At the moment no crash; and the "test App" doesn't lag and connects to WiFi correctly. Let's see if keeps working in the next hours.
CPU usage is high only when lockscreen is active (95-98%) but i think is due to the widget I'm developing, as it uses css animations.
BTW what those 2 **top** lines refer to? I always see them in process list.

```
mobile         10958   0.0  0.0  4197088     16   ??  T     8Jun20   0:00.00 sh -c dpkg-query -s "com.matchstic.xenhtml"
mobile         10957   0.0  0.0  4197088     16   ??  T     8Jun20   0:00.00 sh -c dpkg-query -s "com.matchstic.xenhtml"
```

**Comment by Matchstic** [comment]
@jawsoftware excellent!

My guess is that’s from Filza or your package manager

**Comment by Matchstic** [comment]
v2.0~beta4 is now available which should solve this issue, as noted by jawsoftware
