### ISSUE TITLE
Add/document a Calendar and/or Reminders data provider

### ISSUE THREAD

**Issue by strafe** [Matchstic/Xen-HTML#297]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A data provider for fetching and interacting with Calendar and/or Reminders.

**Describe alternatives you've considered**
Using XenInfo 🤢.

**Additional context**
N/A

**Comment by Matchstic** [comment]
Thanks, this is already planned. See: https://github.com/Matchstic/libwidgetinfo/issues/7
