### ISSUE TITLE
Widget won’t go away

### ISSUE THREAD

**Issue by Tyyab** [Matchstic/Xen-HTML#30]
A widget wallpaper came on my home screen by its self and won’t go away even if I try to Chang the wallpaper or even delete this tweak it stays please help me

**Comment by Matchstic** [comment]
If you've deleted Xen HTML and the issue is still there, it definitely won't be the tweak causing it! Check to see if the widget you were using changes the wallpaper through e.g. Cycript. If so, you can just change the wallpaper back yourself in Settings.
