### ISSUE TITLE
Random Respring while listening to music

### ISSUE THREAD

**Issue by spmdgit** [Matchstic/Xen-HTML#300]
**Describe the bug**

Random respring while listening to music with phone locked and lockscreen off.

**To Reproduce**

Not sure

**Expected behavior**

**Screenshots**

**System Info**

- Device: iPhone 6+
- OS: iOS 12.4.2
- Xen HTML version: e.g. 2.0~beta4

**Additional context**

See crash log from cr4shed

[File Jun 20, 1 11 13 PM.txt](https://github.com/Matchstic/Xen-HTML/files/4809431/File.Jun.20.1.11.13.PM.txt)

**Comment by Matchstic** [comment]
Try changing the Battery Management Mode in Settings > Xen HTML > Advanced to “high”

**Comment by Matchstic** [comment]
Closing due to no feedback
