### ISSUE TITLE
When I try to get new widgets and tap on the various links my setting app crashes. What do I do?

### ISSUE THREAD

**Issue by scmeckels** [Matchstic/Xen-HTML#302]
Bug 

I want to add more widgets but it keeps crashing

**To Reproduce**

1. Open settings
2. Go to xen HTML 
3. Tap on more widgets
4. Tap on any link and it automatically crashes

- Device: [iPhone 10xr]
- OS: [iOS 13.5]
- Xen HTML version: [e.g. 2.0~beta2]

**Comment by Matchstic** [comment]
Fixed in the current public beta
