### ISSUE TITLE
Widget does not show WIFI and carrier info

### ISSUE THREAD

**Issue by Fipps1** [Matchstic/Xen-HTML#311]
**Describe the bug**
No info such as carrier type, wifi network name as well as signal strength for any of them is shown as expected or like before, using xeninfo.

**To Reproduce**
1. Load any widget which is usually able to show this info

**Expected behavior**
Above mentioned info showing

**System Info**
- Device: iPhone SE 2016
- OS: 13.5
- Xen HTML version: 2.0~beta4

**Additional context**
Current widget uses element ids "wifiName, wifiBars, signalNetworkType, signalBars" to call the info. None of them is displayed. Info for weather and battery level shows up as expected.

**Comment by Matchstic** [comment]
This is not yet implemented, and is documented as “to do” elsewhere.

**Comment by Fipps1** [comment]
Thanks for the VERY quick answer! :)
