### ISSUE TITLE
Moonphase code for new moon is not correct

### ISSUE THREAD

**Issue by enaloha** [Matchstic/Xen-HTML#312]
Moonphase codes for new, first quarter, and full moon are not correct.

**Describe the bug**

We have a new moon and { weather.now.moon.phaseCode } should return "NEW", instead it returns "N". I can deal with it, but the documentation or the code should be fixed. The previous phase (WNC) behaved as expected. Maybe check the other codes for accuracy? 

Update: We now have the 1st quarter moon and the phaseCode should return "FQT", but instead returns "FQ"
Update 2: Waxing Gibbous (WXG) is returned correctly. So far we WNC and WXG correct vs NEW (N) and FQT (FQ) incorrect.
Update 3: We now have Full Moon (should return "FUL"), but instead returns "F". So far we WNC and WXG correct vs NEW (N). FQT (FQ), and FUL (F) incorrect.
Update 4: Waning Gibbous (WNG) is returned correctly. So far we WNC, WXG, and WNG correct vs NEW (N). FQT (FQ), and FUL (F) incorrect.
Update 5: Last Quarter (LQT) is wrong and returns "LQ". So far we WNC, WXG, and WNG correct vs NEW (N). FQT (FQ), LQT (LQ), and FUL (F) incorrect.

This completes the returned moonphase codes. As I said, it's no biggy as long as one knows the proper code as outlined above, it's workable.

**To Reproduce**

just show { weather.now.moon.phaseCode } inline

**Expected behavior**

{ weather.now.moon.phaseCode } should return "NEW" at new moon or "FQT" at 1st quarter

**Screenshots**

NA

**System Info**

- Device: [iPhone 11 pro max]
- OS: [13.5]
- Xen HTML version: [2.0~beta4]

**Additional context**

NA

**Comment by Matchstic** [comment]
Thanks, this will be a documentation change.

**Comment by Matchstic** [comment]
Documentation site is now updated to reflect this
