### ISSUE TITLE
Option to Hide Background LS widget too with Music

### ISSUE THREAD

**Issue by deonat0r** [Matchstic/Xen-HTML#32]
It would be great if we are able to hide the Background Ls widget too when Music is playing,like Foreground Widget.

**Comment by Matchstic** [comment]
Which version of iOS would this be for?

**Comment by deonat0r** [comment]
ios 10.3 .

**Comment by deonat0r** [comment]
I requested because the background widget disturbs the now playing view on LS .

**Comment by Matchstic** [comment]
Not going to be adding this, since I don't have access to an iOS 10 device to experiment and  test with
