### ISSUE TITLE
Springboard Crash

### ISSUE THREAD

**Issue by rsherff** [Matchstic/Xen-HTML#326]
**YOU MUST COMPLETE THIS FORM**
This information is asked to help figure out issues. Your issue may be closed without any resolution if you fail to fill out the form.

WHen downloading the tweak works until unlocking the Iphone causing the springboard to crash

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Info**

- Device: [e.g. iPhone 6]
- OS: [e.g. iOS 11.1.2]
- Xen HTML version: [e.g. 2.0~beta2]

**Additional context**

Add any other context about the problem here, such as a link to a crash log.

**Comment by Matchstic** [comment]
Not enough detail filled in with the report. Assuming you’re using the older v1.1.5 on iOS 14, which is known to do that.
