### ISSUE TITLE
No Battery/Weather Information in Widgets

### ISSUE THREAD

**Issue by havoxlife** [Matchstic/Xen-HTML#327]
Description: 
If i add a widget to my homescreen with weather or battery information it doesnt show me any information 

1. Go to + 
2. Click on XEN Html 
3. Scroll down to the Widget i want
4. Placed the widget on my homescreen 
5. Cant see any battery/weather information 

Screenshot:
![5024DA09-96CC-4417-86F2-4E0EF6E54F02](https://user-images.githubusercontent.com/79874134/109556609-53f42a80-7ad7-11eb-81ea-5de17cd046bd.png)

**System Info**

- Device: iPhone 11 Pro
- OS: iOS 14.0.1
- Xen HTML version: 2.0~beta7.1

**Comment by Matchstic** [comment]
Not a bug in Xen HTML. Needs an update to the underlying jailbreak.
