### ISSUE TITLE
weather widgets dont work ios 14.2

### ISSUE THREAD

**Issue by pkanorr02** [Matchstic/Xen-HTML#333]
**Describe the bug**

Weather widgets display { temp } { conditions } ex instead of the actual information

**To Reproduce**

1. use widget that should display weather (im using the watchdogs clock)

**Expected behavior**

When the widget should display weather it displays { temp } { condition } ex

**System Info**

- Device: [e.g. iPhone X]
- OS: [iOS 14.2]
- Xen HTML version: [1.1.5~release]

**Comment by Matchstic** [comment]
Version 1.1.5 doesn’t support iOS 14. Please use the latest beta from https://xenpublic.incendo.ws
