### ISSUE TITLE
Force touching a widget on an image causes a white region to appear

### ISSUE THREAD

**Issue by Matchstic** [Matchstic/Xen-HTML#34]
**Describe the bug**
When 3D touching an image in a widget, such as 03_WW_OFH_LS, and then moving the finger with the same pressure, a white region replaces the image.

**To Reproduce**
1. 3D touch a large image 
2. Move finger whilst applying the same pressure
3. See error

**Expected behavior**
No interaction to be registered.

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 11.1.2

**Additional context**
None

**Comment by leepattison** [comment]
I've had this happen on the HS and LS on my iP6S on 10.3.1 using XENHTML

**Comment by Matchstic** [comment]
Fixed by f1150ef85e7df599631cab7134c4026c48315c6e
