### ISSUE TITLE
Widget stuck behind dock

### ISSUE THREAD

**Issue by Uncommon-34** [Matchstic/Xen-HTML#340]
**Describe the bug**

when i was organising my home screen i had the dock hidden and i put the weather widget behind it and i have been unable to find away to move it or delete it.

**To Reproduce**

Just drag the widget down behind the dock

**System Info**

- Device:  iPhone xs
- OS: iOS 14.2
- Xen HTML version: 2.0

**Comment by Matchstic** [comment]
You can clear all widgets by going to Settings > Xen HTML > Support > Reset all settings
