### ISSUE TITLE
Brightness controller, launch apps with parameters and others

### ISSUE THREAD

**Issue by D4rkTT** [Matchstic/Xen-HTML#342]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
1- Get screen brightness value and able to change it.
2- control wifi, bluetooth, airdrop and airplan mode ( toggel them on or off )
3- launch apps with parameters, like open file from files app directly or launch wifi settings from settings app
4- option to make foreground widget fixed onscreen and don't move it with pages (like background widgets but with foreground options)
5- interact with other tweaks like include functions from them with js (i know its so hard xd)
**Describe alternatives you've considered**
no alternatives

**Additional context**
nothing

**Comment by Matchstic** [comment]
Unfortunately, I no longer work on Xen HTML, meaning this request likely will NOT be fulfilled.

Also... each single point of your request is huge in terms of research and implementation required!

**Comment by D4rkTT** [comment]
oh sad 😢 i dunno that u no longer support xenHTML.
and i know my requests sadly was huge but anyway thank you.
