### ISSUE TITLE
Most recent version causes crash to safemode on 5c, helix jb

### ISSUE THREAD

**Issue by chilaxan** [Matchstic/Xen-HTML#38]
**Describe the bug**
Installing XenHTML on 5c, helix jb, crashes springboard to safemode. Downgrading to v0.4rc1 fixed the issue.

**To Reproduce**
1. install most recent XenHTML on 5c
2. respring
3. ???
4. profit

**Expected behavior**
The tweak would work

**Smartphone (please complete the following information):**
 - Device: iPhone 5c
 - OS: iOS 10.3.3

**Comment by Matchstic** [comment]
I need a crash log please to fix this. Can you install CrashReporter from Cydia, reboot, cause the crash again and send me the logs?

**Comment by chilaxan** [comment]
I’m very sorry but I just left my house to go on vacation. As the 5c is not
my daily driver, I don’t have it with me. I can get you that data in about
a week.

**Comment by vastolorde996** [comment]
hello matheo
i have the same problem h3lix jailbreak iphone 5,2
ios 10.3.3
how to send you the crash report ?

**Comment by Matchstic** [comment]
@chilaxan @vastolorde996 Here's a new build that should fix this issue: https://www.dropbox.com/s/ix0mgfp07o81inm/com.matchstic.xenhtml_0.4rc5-9_iphoneos-arm.deb?dl=0

Please let me know if this works or not!

**Comment by xBreaders** [comment]
@matchstic I tried it on my iPhone 5c with the older version and it wasnt working aswell. I can confirm that its working on the rc5_9 that you send us. It doesnt funcion yet though cuz it says i need to download it from the official repo.

**Comment by xBreaders** [comment]
@matchstic I tried it on my iPhone 5c with the older version and it wasnt working aswell. I can confirm that its working on the rc5_9 that you send us. It doesnt funcion yet though cuz it says i need to download it from the official repo. But the crashes are fixed!

**Comment by pozhiloy-enotik** [comment]
I have iPhone 5, h3lix, ios 10.3.3
same thing
