### ISSUE TITLE
Add toggle to hide Homescreen widgets when a folder is open

### ISSUE THREAD

**Issue by Matchstic** [Matchstic/Xen-HTML#4]
As per the title!

(Note: this may not be necessary on iOS 10)

**Comment by Matchstic** [comment]
Since I no longer have access to an iOS 9 device for testing/prototyping this feature, I'm closing this issue.

**Comment by KevinSnyderCodes** [comment]
Hi, I may be able to help. I'm still running iOS 9.3.3 on my iPhone 6. I have plenty of experience developing in other languages, and recently wanted to get into iOS tweak development. And of course I can be a tester for your work :)
