### ISSUE TITLE
Double click opens magnifying glass

### ISSUE THREAD

**Issue by maestronix** [Matchstic/Xen-HTML#40]
Hi, when double tapping the homescreen and holding it down on the second tap the magnifying glass will open up.
Video posted here: https://imgur.com/JwFt4fL

**Comment by maestronix** [comment]
Additional information:
Device: iPhone 8
iOS Version: 11.3.1

Only tested on the lockscreen

**Comment by Matchstic** [comment]
This is new it seems for iOS 11.3 (or 11.2). Likely is related to #34

**Comment by Matchstic** [comment]
Fixed by 3ce8c9dfe3099f318242688c6822e4ee95008c91
