### ISSUE TITLE
Combination of Background and Foreground Widget

### ISSUE THREAD

**Issue by whiteblacksmiths** [Matchstic/Xen-HTML#42]
Hi, is it possible for the Foreground and Background to be combined in a way that when we swipe to the stock widgets page, the HTML widget that we have would also be swiped to the left (Foreground widget feature) but when we are trying to scroll through the notifications that we have on the main NC page, the widget would not be overlapped?

**Comment by Matchstic** [comment]
Sorry, this isn't something I'm planning to add
