### ISSUE TITLE
XenHTML crashes to safemode on IPhone 7, Electra jailbreak

### ISSUE THREAD

**Issue by StormyTerror39** [Matchstic/Xen-HTML#43]
**Describe the bug**
Installing XenHTML on iphone 7, electra jailbreak, crashes to safemode on first startup screen. I click continue then select continue without importing for lock screen and continue without importing for home screen. These are the only things I can do, but doing this causes the phone to crash to safemode.

**To Reproduce**
1. Install XenHTML
2. respring
3. Select continue without importing
4. Crashes to safemode

**Expected behavior**
i expected to continue without exporting but I crash.

**Smartphone (please complete the following information):**
 - Device: IPhone 7
 - OS: iOS 11.3.1

**Additional context**
Crash reporter doesn't even detect the crash so I cant provide a crash log from that.

**Comment by Matchstic** [comment]
Just making sure, which repo did you install Xen HTML from?

Matt

**Comment by StormyTerror39** [comment]
The electra jailbreak comes with a version of Xen HTML and I used that thinking it might be the most stable

Picture of tweak: https://imgur.com/a/kUrXMFB

**Comment by StormyTerror39** [comment]
ok i used the Xen HTML from your repo and it worked sorry about that

**Comment by Matchstic** [comment]
That’s not the official repo, nor is it the latest version. Please use Xen HTML from http://xenpublic.incendo.ws

**Comment by Matchstic** [comment]
Ah, just seen this come through to my email. Good to hear it works now!
