### ISSUE TITLE
On IOS 11.2 widgets don’t show on homescreen just on lock screen !

### ISSUE THREAD

**Issue by Eternity8321** [Matchstic/Xen-HTML#44]

**Comment by JayTh3Boss1** [comment]
Yea I’m having the same issue haven’t seen a solution to this yet.

**Comment by Eternity8321** [comment]
I hope they fix this issue !!!!! I really love this tweak ! Lol or maybe something else will come up soon !

**Comment by Matchstic** [comment]
Is there any more information regarding this please? Are you trying to use a widget originally intended for the Lockscreen for example?

**Comment by Reapdia99** [comment]
Same having same problem it shows preview but when I go to home screen it doesn’t work (11.2.6) as of 08/23/18
