### ISSUE TITLE
11.3.1 Random Crashes/Crashing PreferenceLoader

### ISSUE THREAD

**Issue by motiivhate** [Matchstic/Xen-HTML#45]
**Describe the bug**
Xen-HTML will crash unexpectedly when selecting Background/Foreground on either Lockscreen or Homescreen options. It's not crashing to safemode, rather the app crashes and appears to crash PreferenceLoader as well because all tweaks in settings will disappear. 

**To Reproduce**
Steps to reproduce the behavior: *Hard to reproduce consistently*
1. Click on Lockscreen or Homescreen
2. Click on Background or Foreground *sometimes it crashes here*
3. Select a widget.
4. Position the widget, and click the check *sometimes it crashes here too*

**Expected behavior**

**Screenshots**

**Smartphone:**
 - Device: iPhone X
 - OS: 11.3.1

**Additional context**
Really hard to reproduce since it seems random, but may be related to PreferenceLoader since when Xen-HTML does crash, all tweaks in settings disappear as well.

**Comment by Matchstic** [comment]
Any chance of a crash report for this please? Will be listed under Preferences in Crash Reporter.

**Comment by pdembowski** [comment]
Yes I’ll email my most recent 3 that list xenhtml as possible reasons

**Comment by Matchstic** [comment]
No response, closing
