### ISSUE TITLE
Bug on iPad 

### ISSUE THREAD

**Issue by Junnioor98** [Matchstic/Xen-HTML#46]
**Describe the bug**
When I instill the tweak and my iPad resets during the set up process on the final step it take me into safe mode and I can’t not exit till the tweak is uninstalled 

**Expected behavior**
Not cause my iPad to go into safe mode 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPad Pro first gen
 - OS: iOS 11.3.1

**Additional context**

**Comment by Matchstic** [comment]
Have you got a crash log at all please?

**Comment by Matchstic** [comment]
Closing due to no response
