### ISSUE TITLE
Settings App Crashes

### ISSUE THREAD

**Issue by Gwarion** [Matchstic/Xen-HTML#47]
iOS 10.2 on 6s+
Jailbroken with double helix.

The settings App crashes when I select "homesceen" in Xen HTML settings 

Edit : video
https://youtu.be/DOEA7x9NH10

Also sent you the crash report through crash reporter at you @incendo.ws address

**Comment by Gwarion** [comment]
Here's a video https://youtu.be/SGvor-CgqFE and I sent you the crash report through crash reporters to your adress @incendo.ws

**Comment by Matchstic** [comment]
Duplicate of #45
