### ISSUE TITLE
homescreen widgets

### ISSUE THREAD

**Issue by RickyX3** [Matchstic/Xen-HTML#50]
I have a music widget installed with xeninfo.. But for some reason I can't change songs using the widget. I have "allow touch on widget enabled", I have disabled it to see if that would fix it but no. Would like this to be fixed, I enjoy Xen HMTL :)

**Comment by ronlbrink** [comment]
I am experiencing the same thing but in addition no music shows in the app

**Comment by Matchstic** [comment]
Likely is an issue with XenInfo, not Xen HTML.
