### ISSUE TITLE
Weather and temperature only updates when weather app is opened

### ISSUE THREAD

**Issue by mattjayres** [Matchstic/Xen-HTML#53]
As the title says, my weather and temperature only update when i open the weather app. I have XenInfo installed. Not sure if anyone else is having this issue.

**Comment by Matchstic** [comment]
That sounds like an issue with XenInfo, not Xen HTML.

**Comment by mattjayres** [comment]
I just emailed junesiphone. I think it is as well, because this has happened using Lock Plus Pro as well.
