### ISSUE TITLE
Widgets not working 

### ISSUE THREAD

**Issue by tmickk** [Matchstic/Xen-HTML#57]
Add available widgets shows widgets “unknown author” and “Package: unknown / local”. 
I tried reset all settings in XenHtml, go nuclear. I import lockhtml and my phone crashes to safemode, I check continue with out import and continue to import sbhtml and crash to safemode again. As long as I setup without import i can continue but widgets don’t work. Test widgets do show. I’ve tried everything suggested on discord but nothing helpful.

**Comment by Matchstic** [comment]
What's the issue you're having? I'm not understanding too well.

**Comment by tmickk** [comment]
I have iPhone X on ios 11.3.1 Electra jailbreak. Xenhtml does not show widgets. All available widgets for both LS and HS have list “author unknown” and “ Package: unknown / local. I tried Xenhtml Support reset all settings to try getting widgets working. Xenhtml starts fresh with option to import widgets. I click that and my phone crashes to safe mode. I respring and Xenhtml starts with setup again. I ckick continue without importing widgets and it continues. I click import homescreen widgets and my phone crashes to safe mode again. I respring and Xenhtml starts with setup again. I click continue without import for lockscreen and then click continue without import for homescreen and Xenhtml starts but with available widgets having the same  “author unknown” and “ Package: unknown / local”. No preview no widget showing when selected.

Sent from Mail for Windows 10

**Comment by Matchstic** [comment]
Having Unknown Author is normal if the widgets weren’t installed from Cydia, or you updated iOS version without previously removing them. 

As to widgets not showing, is that in the UI where you can see your wallpaper etc?

**Comment by tmickk** [comment]
Yes, nothing shows on lockscreen or homescreen or from the i preview or when set on either L or H

Sent from Mail for Windows 10

**Comment by tmickk** [comment]
Also I never had any widgets on this phone before. 11.3.1 is the first jailbreak on this phone.
I did download an old widget from cydia “ BuufJuiced McFly UniAW7.1 WW2- 2016 and it shows works great.

Sent from Mail for Windows 10
