### ISSUE TITLE
Add support for the Homescreen to have different widgets per page

### ISSUE THREAD

**Issue by Matchstic** [Matchstic/Xen-HTML#6]
Like the old tweak PerPageHTML used to do, have different HTML widgets per each SpringBoard page.

**Comment by NoisyFlake** [comment]
+1

**Comment by daproject85** [comment]
hey are you sure this has been implemented??

**Comment by iAzaleea** [comment]
Yes please!! This would be great!

**Comment by MiladShojaei** [comment]
i need this . please add this feature

**Comment by Matchstic** [comment]
At long last, I'm actually working on this. Making good progress too!

Remaining steps for it:
- [ ] Add implementation for dragging around widgets
- [ ] Fix issue where touches though blank parts of the widget is impossible

**Comment by Matchstic** [comment]
Tracking this in the branch, feature-homescreen-fg-widgets.

Remaining tasks:

- [ ] Display a line down the y axis when moving widgets, to help alignment
- [ ] Whitelist the new foreground views for touch forwarding to the background views (see XENHTouchForwardingRecognizer.m, line 153) (mainly checking for the RootContent UIView of WKWebView and equivalent for UIWebView, and forwarding on those)
- [ ] Display the user's wallpaper behind widget previews in the foreground widget picker
- [ ] Add a basic Settings sub-panel for the feature (maybe?)

**Comment by Matchstic** [comment]
Merged and released as v0.5
