### ISSUE TITLE
Cityscapeslivewallpaper

### ISSUE THREAD

**Issue by piverson** [Matchstic/Xen-HTML#64]
I found a cityscapeslivewallpaper on cydia but it doesn't seem to be from your creation and wen i try to install it it wants to install someone else's xen html ? Do i figure it's a bootleg cityscapeslivewallpaper.... Can you add this to your repo please.... Thank you for your time

**Comment by Matchstic** [comment]
Please make sure to not install packages from unofficial repositories. Plus, my repo only will host Xen HTML - there should be a official repo for the widget you want to use.
