### ISSUE TITLE
Open in buttons not working

### ISSUE THREAD

**Issue by guillaumeseur** [Matchstic/Xen-HTML#65]
Alien blue > open in safari 
Safari chariz > open in cydia
...
All not working.
Tried disabling all tweaks in iCleaner and the tweak that interferes with this problem is xenHTML

**Comment by Matchstic** [comment]
I'm not able to reproduce this issue, and have not heard of anyone else experiencing it. Which version of iOS is this on?

**Comment by guillaumeseur** [comment]
Thanks for the fast response.
I’m using iPad pro 12.9 2018, iOS 11.3.1
It seems that the problem occurs when it has to open a new window.
[XenHTML disabled](https://imgur.com/a/vKDLcRe)
[XenHTML enabled](https://imgur.com/a/nOM8N1r)
