### ISSUE TITLE
Xen HTML issue

### ISSUE THREAD

**Issue by Zennitoid** [Matchstic/Xen-HTML#69]
After downloading Xen HTML, when I respring it instantly puts me in a respring loop. Tried couple of times already by uninstalling and reinstalling in safe mode but same issue comes up. I’m using the uncover jailbreak iOS 11.3.1.
And yes, I’m installing from the official Xen HTML repo: http://xenpublic.incendo.ws

**Comment by Matchstic** [comment]
Is this the first time installing the tweak?

**Comment by Matchstic** [comment]
Hmm. I must have broken something with the first time setup UI then. 

For now, I’ve pulled the newest update. Installing 0.4rc6 via Cydia’s downgrade option will get you a recent version of the tweak that doesn’t have this issue.

**Comment by Zennitoid** [comment]
Ok thx, that solved the problem for me

**Comment by Matchstic** [comment]
New update is available to fix the respring loop. Please let me know if it works!

**Comment by Zennitoid** [comment]
Sry for the late reply. Yup the new update works perfectly fine.

**Comment by Matchstic** [comment]
Great! Closing the issue :)
