### ISSUE TITLE
Landscape

### ISSUE THREAD

**Issue by jffortier249** [Matchstic/Xen-HTML#70]
Iphone 8+
Orientation icon is turn off
Setting up a page layout in home screen

Play a game on horizontal ( in my case is was Homescape)and going back to home screen still in horizontal make the layout shift location and misaligned items. 

Quit the game with device in vertical mode, no problem. ![Alt text](https://www.dropbox.com/s/262q3slk45g3sff/IMG_1812.JPG?dl=0)

![Alt text](https://www.dropbox.com/s/84xgypftii05j9j/IMG_1813.JPG?dl=0)

**Comment by Matchstic** [comment]
I can't test this without a '+' iPhone, or a 'Max' iPhone, but should hopefully be fixed with commit: 6358f37ddc500742c6a039927604a7419d910475
