### ISSUE TITLE
weather and battery doesn’t shown 

### ISSUE THREAD

**Issue by qwaleed** [Matchstic/Xen-HTML#77]
The is an issue with this tweak which lets the weather and battery doesn’t shown ![Alt text](https://share.icloud.com/photos/03rde71x3nxgqpY0T7IaR0JYg)

**Comment by Matchstic** [comment]
Make sure to also have XenInfo installed.

**Comment by qwaleed** [comment]
When I download it it’s lead me to safemood. Could you provide a source
which has all XenHTML and XenInfo

**Comment by Matchstic** [comment]
https://junesiphone.com/supersecret/ has XenInfo available for free - you do not need to pay to access this repo for that package only.
