### ISSUE TITLE
Lock screen Duration not working

### ISSUE THREAD

**Issue by KeyFlyz** [Matchstic/Xen-HTML#79]
Set lock screen duration to 2 minutes and it doesn’t work just shuts back off after a few seconds like normal. 
iPhone 8+ IOS 12.0.1

**Comment by Matchstic** [comment]
This is a known issue with using the tweak with substrate on iOS 11.3 and higher.

**Comment by Matchstic** [comment]
Fixed with commit 2a82e9ea65f1be935adc10296f1dd998bc3e9e6c, not sure when it'll be in a public release
