### ISSUE TITLE
Allow for global configuration of LockScreen or Homescreen

### ISSUE THREAD

**Issue by nickmc01** [Matchstic/Xen-HTML#80]
I know right now you can add widgets as you like and they work independently. But I was wondering if it could be possible to do global configuration for either the LockScreen or the Homescreen? For example, if I wanted to make all elements on the homescreen fade in and out, I would need to manually edit each widget.

**Comment by Matchstic** [comment]
That’s not something I’m planning to add, sorry. Interesting idea however :)
