### ISSUE TITLE
Overheating 

### ISSUE THREAD

**Issue by pqhcker** [Matchstic/Xen-HTML#81]
Hi Matt.. I have installed XenHTML, and I have a Ryu_004Blue widget on  LS, and HS.Ryu_006 Fluid Widget Transparent on HS, after iOS 12 all  works fine, but now if XenHTML is active is causing overeat in my device.

**Comment by Matchstic** [comment]
Your issue isn't Xen HTML. That fluid widget is! It's known to be incredibly battery intensive.

**Comment by pqhcker** [comment]
Oh... Ok. Thanks!

Saludos,
