### ISSUE TITLE
IOS 12 compatibility simpleLS

### ISSUE THREAD

**Issue by ACEWRITER** [Matchstic/Xen-HTML#84]
When I scroll my notifications I find that the stuff in SimpleLS goes over my notifications, it did not happen before xenhtml was installed, could you make it so this will not happen?

**Comment by Matchstic** [comment]
This is a known issue, where the stock clock somehow is “frozen” in place. It’s a weird one.

**Comment by Matchstic** [comment]
Closing due to being a duplicate of #65
