### ISSUE TITLE
Notifications fail to appear on lock screen and the notification center until you open the control center.

### ISSUE THREAD

**Issue by Proaxel** [Matchstic/Xen-HTML#86]
For some reason that I can't pinpoint, XenHTML is causing any notifications that are supposed to come up on your lock screen and the notification center to be hidden. I know this because this does not happen when the toggle to enable the tweak for the lock screen is disabled. When the device does get a notification, the screen wakes up, but no notification appears. Scrolling down in order to view earlier notifications does not work either.

It was just yesterday that I found a workaround. When I open and close the control center, the notifications show themselves until the next time the screen goes to sleep.

I am using an iPhone 6s+ running iOS 11.3.1.

Here is a video I took with my not-so-great computer webcam showing the issue:

![ezgif-1-5444cb7e9d21](https://user-images.githubusercontent.com/9545347/54500390-a54e8380-48d9-11e9-8f79-60150df5915a.gif)

**Comment by Proaxel** [comment]
Issue is still present as of the 0.4RC8 update.

**Comment by Matchstic** [comment]
Is this still an issue?

**Comment by Proaxel** [comment]
Seems to be fixed as of 0.5.3, though I’m not 100% sure if it was actually fixed or if I accidentally did something on my end.

Also sorry @matchstic for not replying earlier, I don’t track my Github notifications as closely as I should be. If you did fix this, thanks a bunch! It took a while but at least we got there.

**Comment by Matchstic** [comment]
No worries! If it’s fixed your end, then I’m happy to close this.
