### ISSUE TITLE
Wrong home screen orientation on iPad Pro 10.5

### ISSUE THREAD

**Issue by imxieyi** [Matchstic/Xen-HTML#89]
**Describe the bug**
Wrong orientation on home screen on iPad Pro 10.5. If I rotate the screen and then rotate back, it would return to normal. However, the next time it is launched, it is still buggy. The lock screen has no issue at all. The notification center also has this issue while dragging, though it behaves as lock screen.

**To Reproduce**
1. Install on iPad.
2. The setup interface on home screen is already buggy.

**Expected behavior**
Whether I rotate the screen or not, the widget should always fill the entire screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/20365903/54860899-efad8580-4d5b-11e9-91f6-3de0ffddd720.png)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 10.5
 - OS: iOS 12.1.1

**Comment by cnassaney** [comment]
Same issue on 12" ipad pro.

**Comment by cnassaney** [comment]
![IMG_0420](https://user-images.githubusercontent.com/1091309/62092829-9f739200-b22b-11e9-9f79-a42d2195364e.png)

Problem still exists on large iPad Pro in landscape mode. Just installed latest update of software from Cydia.
