### ISSUE TITLE
Nc widget not responding

### ISSUE THREAD

**Issue by alchafocus** [Matchstic/Xen-HTML#9]
Sometime widgets that can be interact with, become not responsive in notification center today tab, when it can be interact in xen's NC Widget with no problem or vice versa. (I'm using fantastical2, calculator+, and snapstats widger btw)
Thanks

**Comment by Matchstic** [comment]
Thanks for the report, though sounds like you've accidentally placed this issue in the wrong repo. Can you re-post this over at https://github.com/Matchstic/Xen/issues please, and I'll close this one here.

**Comment by alchafocus** [comment]
Done matt, thankyou :)
