### ISSUE TITLE
Open app by clicking on the widget

### ISSUE THREAD

**Issue by WendelFelius** [Matchstic/Xen-HTML#90]
It would be nice if you can open an app by clicking on the widget. For instance; my widget shows me the date, so by clicking on it i would like to open Calendar.app 🤘🏻

**Comment by Matchstic** [comment]
This is something for widgets themselves to add, so not something on my end!

**Comment by MaxLeiter** [comment]
@Matchstic for xenhtmls successor, I don't think this is within a widgets capability if the app doesn't have a URL scheme

**Comment by Matchstic** [comment]
> xenhtmls successor

Xen HTML is still an active project.

Regarding the ticket, this is doable by widget developers if they use XenInfo etc.
