### ISSUE TITLE
Documentation's site download links are broken

### ISSUE THREAD

**Issue by mileyvirus** [Matchstic/Xen-HTML#96]
[In the docs](https://incendo.ws/documentation/xenhtml/) we have:

> Example widget using WidgetInfo.plist: [download here](https://incendo.ws/projects/XenHTML/downloads/WidgetInfoPlistExampleWidget.zip).

> Example Options.plist: [download here](https://incendo.ws/projects/XenHTML/downloads/Options.plist.zip).

These point both to broken links. I found however that the files are still somewhere, I guess you changed some directories.

The correct links are:
https://incendo.ws/documentation/xenhtml/downloads/WidgetInfoPlistExampleWidget.zip
https://incendo.ws/documentation/xenhtml/downloads/Options.plist.zip

**Comment by Matchstic** [comment]
Thanks, I missed this when re-organising my web stuff!
